<?php

namespace App\V1\Providers;

use App\V1\Models\Patient\Card\ArchiveNumber;
use Illuminate\Support\Facades\Gate;
use Illuminate\Foundation\Support\Providers\AuthServiceProvider as ServiceProvider;

class AuthServiceProvider extends ServiceProvider
{
    /**
     * Register any authentication / authorization services.
     *
     * @return void
     */
    public function boot()
    {
        $this->registerPolicies();
    }

    /**
     * The policy mappings for the application.
     *
     * @var array
     */
    protected $policies = [
        'App\V1\Http\Controllers\Reports\CallCenterController' => 'App\V1\Policies\Reports\CallCenterPolicy',
        'App\V1\Http\Controllers\Reports\FinanceController' => 'App\V1\Policies\Reports\FinancePolicy',
        'App\V1\Http\Controllers\Reports\MarketingController' => 'App\V1\Policies\Reports\MarketingPolicy',
        'App\V1\Models\User' => 'App\V1\Policies\UserPolicy',
        'App\V1\Models\Clinic' => 'App\V1\Policies\ClinicPolicy',
        'App\V1\Models\Employee' => 'App\V1\Policies\EmployeePolicy',
        'App\V1\Models\Employee\Clinic' => 'App\V1\Policies\Employee\ClinicPolicy',
        'App\V1\Models\Employee\Position' => 'App\V1\Policies\Employee\PositionPolicy',
        'App\V1\Models\Employee\Document' => 'App\V1\Policies\Employee\DocumentPolicy',
        'App\V1\Models\Employee\Education' => 'App\V1\Policies\Employee\EducationPolicy',
        'App\V1\Models\Employee\Qualification' => 'App\V1\Policies\Employee\QualificationPolicy',
        'App\V1\Models\Employee\Speciality' => 'App\V1\Policies\Employee\SpecialityPolicy',
        'App\V1\Models\Employee\ScienceDegree' => 'App\V1\Policies\Employee\ScienceDegreePolicy',
        'App\V1\Models\Specialization' => 'App\V1\Policies\SpecializationPolicy',
        'App\V1\Models\CallRequest' => 'App\V1\Policies\CallRequestPolicy',
        'App\V1\Models\Patient' => 'App\V1\Policies\PatientPolicy',
        'App\V1\Models\Ehealth\Patient' => 'App\V1\Policies\Ehealth\PatientPolicy',
        'App\V1\Models\Ehealth\Patient\Authentication' => 'App\V1\Policies\Ehealth\Patient\AuthenticationPolicy',
        'App\V1\Models\CallRequest\Purpose' => 'App\V1\Policies\CallRequest\PurposePolicy',
        'App\V1\Models\Appointment' => 'App\V1\Policies\AppointmentPolicy',
        'App\V1\Models\Server' => 'App\V1\Policies\ServerPolicy',
        'App\V1\Models\SessionLog' => 'App\V1\Policies\SessionLogPolicy',
        'App\V1\Models\TreatmentCourse' => 'App\V1\Policies\TreatmentCoursePolicy',
        'App\V1\Models\TreatmentCourse\Document' => 'App\V1\Policies\TreatmentCourse\DocumentPolicy',
        'App\V1\Models\Appointment\Status' => 'App\V1\Policies\Appointment\StatusPolicy',
        'App\V1\Models\Appointment\Service' => 'App\V1\Policies\Appointment\ServicePolicy',
        'App\V1\Models\Appointment\Note' => 'App\V1\Policies\Appointment\NotePolicy',
        'App\V1\Models\Handbook' => 'App\V1\Policies\HandbookPolicy',
        'App\V1\Models\Call\Result' => 'App\V1\Policies\Call\ResultPolicy',
        'App\V1\Models\Call' => 'App\V1\Policies\CallPolicy',
        'App\V1\Models\PersonalTask' => 'App\V1\Policies\PersonalTaskPolicy',
        'App\V1\Models\DaySheet' => 'App\V1\Policies\DaySheetPolicy',
        'App\V1\Models\Call\DeleteReason' => 'App\V1\Policies\Call\DeleteReasonPolicy',
        'App\V1\Models\Appointment\DeleteReason' => 'App\V1\Policies\Appointment\DeleteReasonPolicy',
        'App\V1\Models\Diagnosis' => 'App\V1\Policies\DiagnosisPolicy',
        'App\V1\Models\Patient\Card' => 'App\V1\Policies\Patient\CardPolicy',
        'App\V1\Models\Patient\Card\Specialization' => 'App\V1\Policies\Patient\Card\SpecializationPolicy',
        'App\V1\Models\PriceAgreementAct' => 'App\V1\Policies\PriceAgreementActPolicy',
        'App\V1\Models\PriceAgreementAct\Price' => 'App\V1\Policies\PriceAgreementAct\PricePolicy',
        'App\V1\Models\Service' => 'App\V1\Policies\ServicePolicy',
        'App\V1\Models\Analysis' => 'App\V1\Policies\AnalysisPolicy',
        'App\V1\Models\Service\PaymentDestination' => 'App\V1\Policies\Service\PaymentDestinationPolicy',
        'App\V1\Models\Price' => 'App\V1\Policies\PricePolicy',
        'App\V1\Models\Analysis\Result' => 'App\V1\Policies\Analysis\ResultPolicy',
        'App\V1\Models\Call\CallLog' => 'App\V1\Policies\Call\CallLogPolicy',
        'App\V1\Models\Call\ProcessLog' => 'App\V1\Policies\Call\ProcessLogPolicy',
        'App\V1\Models\Analysis\Laboratory' => 'App\V1\Policies\Analysis\LaboratoryPolicy',
        'App\V1\Models\Analysis\Template' => 'App\V1\Policies\Analysis\TemplatePolicy',
        'App\V1\Models\Appointment\Limitation' => 'App\V1\Policies\Appointment\LimitationPolicy',
        'App\V1\Models\Role' => 'App\V1\Policies\RolePolicy',
        'App\V1\Models\Permission' => 'App\V1\Policies\PermissionPolicy',
        'App\V1\Models\Workspace' => 'App\V1\Policies\WorkspacePolicy',
        'App\V1\Models\Workspace\Clinic' => 'App\V1\Policies\Workspace\ClinicPolicy',
        'App\V1\Models\Appointment\Status\Reason' => 'App\V1\Policies\Appointment\Status\ReasonPolicy',
        'App\V1\Models\Specialization\Clinic' => 'App\V1\Policies\Specialization\ClinicPolicy',
        'App\V1\Models\FileAttachment' => 'App\V1\Policies\FileAttachmentPolicy',
        'App\V1\Models\Patient\InformationSource' => 'App\V1\Policies\Patient\InformationSourcePolicy',
        'App\V1\Models\Patient\SignalRecord' => 'App\V1\Policies\Patient\SignalRecordPolicy',
        'App\V1\Models\Patient\Card\RecordTemplate' => 'App\V1\Policies\Patient\Card\RecordTemplatePolicy',
        'App\V1\Models\Patient\Card\ProtocolTemplate' => 'App\V1\Policies\Patient\Card\ProtocolTemplatePolicy',
        'App\V1\Models\Handbook\PatientDocument' => 'App\V1\Policies\PatientDocumentPolicy',
        'App\V1\Models\Patient\Card\OutpatientRecord' => 'App\V1\Policies\Patient\Card\OutpatientRecordPolicy',
        'App\V1\Models\Patient\Card\DiaryRecord' => 'App\V1\Policies\Patient\Card\DiaryRecordPolicy',
        'App\V1\Models\Patient\Card\ServiceRecord' => 'App\V1\Policies\Patient\Card\ServiceRecordPolicy',
        'App\V1\Models\Patient\Card\ProtocolRecord' => 'App\V1\Policies\Patient\Card\ProtocolRecordPolicy',
        'App\V1\Models\Patient\Card\OutclinicProtocolRecord' => 'App\V1\Policies\Patient\Card\OutclinicProtocolRecordPolicy',
        'App\V1\Models\Patient\Card\Record' => 'App\V1\Policies\Patient\Card\RecordPolicy',
        'App\V1\Models\Patient\Card\Document' => 'App\V1\Policies\Patient\Card\DocumentPolicy',
        'App\V1\Models\Patient\Card\NextVisit' => 'App\V1\Policies\Patient\Card\NextVisitPolicy',
        'App\V1\Models\Patient\Card\ArchiveNumber' => 'App\V1\Policies\Patient\Card\ArchivedNumberPolicy',
        'App\V1\Models\Patient\Card\PrintedDocument' => 'App\V1\Policies\Patient\Card\PrintedDocumentPolicy',
        'App\V1\Models\Patient\IssuedMedicine' => 'App\V1\Policies\Patient\IssuedMedicinePolicy',
        'App\V1\Models\DiscountCardType\NumberingKind' => 'App\V1\Policies\DiscountCardType\NumberingKindPolicy',
        'App\V1\Models\DiscountCardType\Icon' => 'App\V1\Policies\DiscountCardType\IconPolicy',
        'App\V1\Models\DiscountCardType' => 'App\V1\Policies\DiscountCardTypePolicy',
        'App\V1\Models\ActionLog' => 'App\V1\Policies\ActionLogPolicy',
        'App\V1\Models\MedicineStore' => 'App\V1\Policies\MedicineStorePolicy',
        'App\V1\Models\MedicineFirm' => 'App\V1\Policies\MedicineFirmPolicy',
        'App\V1\Models\Medicine' => 'App\V1\Policies\MedicinePolicy',
        'App\V1\Models\PaymentMethod' => 'App\V1\Policies\PaymentMethodPolicy',
        'App\V1\Models\Patient\IssuedDiscountCard' => 'App\V1\Policies\Patient\IssuedDiscountCardPolicy',
        'App\V1\Models\Patient\AssignedMedicine' => 'App\V1\Policies\Patient\AssignedMedicinePolicy',
        'App\V1\Models\Patient\Card\Assignment' => 'App\V1\Policies\Patient\Card\AssignmentPolicy',
        'App\V1\Models\Patient\AssignedService' => 'App\V1\Policies\Patient\AssignedServicePolicy',
        'App\V1\Models\Patient\Registration' => 'App\V1\Policies\Patient\RegistrationPolicy',
        'App\V1\Models\Patient\User' => 'App\V1\Policies\Patient\UserPolicy',
        'App\V1\Models\Patient\Card\TreatmentAssignment' => 'App\V1\Policies\Patient\Card\TreatmentAssignmentPolicy',
        'App\V1\Models\Patient\Card\ConsultationRecord' => 'App\V1\Policies\Patient\Card\ConsultationRecordPolicy',
        'App\V1\Models\Patient\Upload' => 'App\V1\Policies\Patient\UploadPolicy',
        'App\V1\Models\CashierSessionLog' => 'App\V1\Policies\CashierSessionLogPolicy',
        'App\V1\Models\Employee\Cashbox' => 'App\V1\Policies\Employee\CashboxPolicy',
        'App\V1\Models\Payment' => 'App\V1\Policies\PaymentPolicy',
        'App\V1\Models\SiteEnquiry' => 'App\V1\Policies\SiteEnquiryPolicy',
        'App\V1\Models\Employee\OperatorBonus' => 'App\V1\Policies\Employee\OperatorBonusPolicy',
        'App\V1\Models\Clinic\BonusNorm' => 'App\V1\Policies\Clinic\BonusNormPolicy',
        'App\V1\Models\Clinic\Group' => 'App\V1\Policies\Clinic\GroupPolicy',
        'App\V1\Models\Employee\OutclinicMedicine' => 'App\V1\Policies\Employee\OutclinicMedicinePolicy',
        'App\V1\Models\Employee\OutclinicSpecialization' => 'App\V1\Policies\Employee\OutclinicSpecializationPolicy',
        'App\V1\Models\Employee\OutclinicDiagnostic' => 'App\V1\Policies\Employee\OutclinicDiagnosticPolicy',
        'App\V1\Models\Notification\Channel' => 'App\V1\Policies\Notification\ChannelPolicy',
        'App\V1\Models\Notification\Template' => 'App\V1\Policies\Notification\TemplatePolicy',
        'App\V1\Models\Notification\MailingProvider' => 'App\V1\Policies\Notification\MailingProviderPolicy',
        'App\V1\Models\Notification\MailingTemplate' => 'App\V1\Policies\Notification\MailingTemplatePolicy',
        'App\V1\Models\InsuranceCompany' => 'App\V1\Policies\InsuranceCompanyPolicy',
        'App\V1\Models\InsuranceCompany\Clinic' => 'App\V1\Policies\InsuranceCompany\ClinicPolicy',
        'App\V1\Models\Patient\InsurancePolicy' => 'App\V1\Policies\Patient\InsurancePolicyPolicy',
        'App\V1\Models\LaboratoriesSchedule' => 'App\V1\Policies\LaboratoriesSchedulePolicy',
        'App\V1\Models\SiteEnquiry\Service' => 'App\V1\Policies\SiteEnquiry\ServicePolicy',
        'App\V1\Models\Country' => 'App\V1\Policies\CountryPolicy',
        'App\V1\Models\InsuranceCompany\Act' => 'App\V1\Policies\InsuranceCompany\ActPolicy',
        'App\V1\Models\DaySheet\TimeBlockReason' => 'App\V1\Policies\DaySheet\TimeBlockReasonPolicy',
        'App\V1\Models\Employee\DoctorIncomePlan' => 'App\V1\Policies\Employee\DoctorIncomePlanPolicy',
        'App\V1\Models\Patient\Prepayment' => 'App\V1\Policies\Patient\PrepaymentPolicy',
        'App\V1\Models\EmailLog' => 'App\V1\Policies\EmailLogPolicy',
        'App\V1\Models\LegalEntity' => 'App\V1\Policies\LegalEntityPolicy',
        'App\V1\Models\LegalEntity\Clinic' => 'App\V1\Policies\LegalEntity\ClinicPolicy',
        'App\V1\Models\Msp' => 'App\V1\Policies\MspPolicy',
        'App\V1\Models\Msp\Contract' => 'App\V1\Policies\Msp\ContractPolicy',
        'App\V1\Models\Ehealth\Application' => 'App\V1\Policies\Ehealth\ApplicationPolicy',
        'App\V1\Models\Ehealth\CareEpisode' => 'App\V1\Policies\Ehealth\CareEpisodePolicy',
        'App\V1\Models\SmsAppointmentReminder' => 'App\V1\Policies\SmsAppointmentReminderPolicy',
        'App\V1\Models\WaitListRecord' => 'App\V1\Policies\WaitListRecordPolicy',
        'App\V1\Models\Clinic\MoneyReciever' => 'App\V1\Policies\Clinic\MoneyRecieverPolicy',
        'App\V1\Models\Appointment\VideoSession' => 'App\V1\Policies\VideoChatPolicy',
        'App\V1\Models\CacheValidity' => 'App\V1\Policies\CacheValidityPolicy',
        'App\V1\Models\Patient\ClinicRoute' => 'App\V1\Policies\Patient\ClinicRoutePolicy',
        'App\V1\Models\Clinic\ServiceType' => 'App\V1\Policies\Clinic\ServiceTypePolicy',
        'App\V1\Models\Employee\ServiceType' => 'App\V1\Policies\Employee\ServiceTypePolicy',
        'App\V1\Models\Department' => 'App\V1\Policies\DepartmentPolicy',
        'App\V1\Models\Department\Room' => 'App\V1\Policies\Department\RoomPolicy',
        'App\V1\Models\Department\Room\Occupation' => 'App\V1\Policies\Department\Room\OccupationPolicy',
        'App\V1\Models\ExchangeRate' => 'App\V1\Policies\ExchangeRatePolicy',
        'App\V1\Models\Appointment\Status\DelayReason' => 'App\V1\Policies\Appointment\Status\DelayReasonPolicy',
        'App\V1\Models\Appointment\Delay' => 'App\V1\Policies\Appointment\DelayPolicy',
        'App\V1\Models\Analysis\Candidate' => 'App\V1\Policies\Analysis\CandidatePolicy',
        'App\V1\Models\Analysis\Laboratory\Container' => 'App\V1\Policies\Analysis\Laboratory\ContainerPolicy',
        'App\V1\Models\Analysis\Laboratory\TransferSheet' => 'App\V1\Policies\Analysis\Laboratory\TransferSheetPolicy',
        'App\V1\Models\Patient\Card\ConditionRecord' => 'App\V1\Policies\Patient\Card\ConditionRecordPolicy',
        'App\V1\Models\DaySheet\LockLog' => 'App\V1\Policies\LockLogPolicy',
        'App\V1\Models\ReasonUnblock' => 'App\V1\Policies\ReasonUnblockPolicy',
        'App\V1\Models\Notification\Setting\Clinic' => 'App\V1\Policies\Notification\SettingClinicPolicy',
        'App\V1\Models\Notification\MailingSetting\MailingClinic' => 'App\V1\Policies\Notification\MailingSetting\NotificationMailingTemplateSettingClinicPolicy',
        'App\V1\Models\Notification' => 'App\V1\Policies\NotificationPolicy',
        'App\V1\Models\AmbulanceCall' => 'App\V1\Policies\AmbulanceCallPolicy',
        'App\V1\Models\Patient\Card\ManipulationRecord' => 'App\V1\Policies\Patient\Card\ManipulationRecordPolicy',
        'App\V1\Models\Checkbox\Shift' => 'App\V1\Policies\Checkbox\ShiftPolicy',
        'App\V1\Models\MoneyRecieverCashbox' => 'App\V1\Policies\MoneyRecieverCashboxPolicy',
        'App\V1\Models\CashierCheckboxCashbox' => 'App\V1\Policies\CashierCheckboxCashboxPolicy',
        'App\V1\Models\Checkbox\Check' => 'App\V1\Policies\Checkbox\CheckPolicy',
    ];
}
