import fileLoader from '@/services/file-loader';
import Sketchpad from '@/vendors/responsive-sketchpad';
import QRCode from 'qrcode';
import html2canvas from 'html2canvas';

const FONT_DATA = 'AAEAAAAPAIAAAwBwRkZUTU5xNrgAAF8oAAAAHEdERUYC/QHSAABWmAAAADhHUE9T/qAJ2AAAV6gAAAd+R1NVQtWK2DQAAFbQAAAA2E9TLzJuStSqAAABeAAAAGBjbWFwDFSlYQAABYAAAAI6Z2FzcP//AAMAAFaQAAAACGdseWbYVMxyAAAJlAAAP5xoZWFkBB40iQAAAPwAAAA2aGhlYQcvBIUAAAE0AAAAJGhtdHgVOyR3AAAB2AAAA6hsb2NhRZU2IgAAB7wAAAHWbWF4cAEzAEYAAAFYAAAAIG5hbWX2+rvqAABJMAAAB55wb3N0rZp5DgAAUNAAAAXAAAEAAAABAAAZHNafXw889QALA+gAAAAA0Hf4ewAAAADQd/h7/9z/KgQzA4QAAAAIAAIAAAAAAAAAAQAAAsr/QQBTBHz/3P/dBDMAAQAAAAAAAAAAAAAAAAAAAOoAAQAAAOoAQwAHAAAAAAACAAAAAQABAAAAQAAAAAAAAAACAc8CJgAFAQACvAKKAAAAjAK8AooAAAHdADIA+gAAAgAGAwUAAAIABIAAAgsQAABIAAAAAAAAAABQWVJTAAAAIOABAsr/QQBTA4QA1gAAAAQCAAAAAgQCyAAAACAABAPoAAAAAAAAAU0AAAEWAAABFgBKAbwAVQIsAA8CLAANA+gAVwKIACEBFgBZARYAMgEW//cBcgASAlgAKgEWAEcBhQAwARYARwFg/+4CLAAkAiwAUQIsABcCLAAbAiwAGQIsABwCLAAkAiwAJQIsACACLAAeARYARwEWAEcCWAAqAlgAKgJYACoCLAAsAyAAHQKb//gCwABKAtIAKgLSAEsCdgBKAlEASwL3ACoC0gBJARYATAIZABkCrQBKAj4ASgN5AEsC0gBJAvgAJgKbAE0C+AAmAsAASgKIACACUQAHAtIARQJj//sDsAAIAoj/+gKI//sCdgATASgARwFgAAMBKAABAlgAUAH0AAAA8f/cAiwAIQJjAD0CLAAlAmMAJwIsACIBOwAKAlEAJAI+AD0A8QA/APH/7QIZAD0A8QBAA2YAPQI+AD0CUQAkAmMAPgJjACcBYAAyAgcAHwFNAAgCPgA8AgcACAMKAAwCGQADAgcAAwH0ABYBKP/oAN4APQEo/+gCWAAhAiwAIQIsACIA3gA9AiwAGQMgABsBzwAyAlgAKgGQAA0BkAAnAlgAKgI+ADgCWAARARYARwHPAD0CWAAqAiwAAAJ2AEoDCgAIAjMATALSACsCiAAgARYATAEW/+8CGQAZBAsACAQLAEkDCgAIAq0ASgJj//sC0gBJApv/+ALAAEwCwABKAjMATALSAAUCdgBKBBP/+QKIACAC0gBJAtIASQKtAEoCwAAIA3kASwLSAEkC+AAmAtIASQKbAE0C0gAqAlEABwJj//sDJwAiAoj/+gLeAEYCrQAyBDEASQQ9AEYDLQAIA4AATAKbAEwC0gApA/oASQKt//MCLAAhAlEALwIsADwBqgA8AlgABwIsACIDCv/3AgcAHQI+ADwCPgA8AhkAPAI+AA0CwAA8Aj4APAJRACQCPgA8AmMAPgIsACUB0AAFAgcAAwM6ACQCGQADAk4APAIZACQDLgA8Az4APAJ2AAYC0gA3AhkAPAIsACADIgA8Aiz/+AIsACICPgAPAaoAPAIsACUCBwAfAPEAPwDx/90A8f/tAzEACgMxADwCPgAPAhkAPAIHAAMCPgA8AjMATAGqADwB9AAAA+gAAAEWAEMBFgBJARYATQG8ADsBvAA8AbwAPQIsACECLAAhAfQASAPoAGwEfABPAQMAKwEDAD0ELABHA94AZwKqAAoCWAAKAxwALAJYACECWAApAlgAJgJYAC0BhQAwARYAAAAAAAMAAAADAAAAHAABAAAAAAE0AAMAAQAAABwABAEYAAAAQgBAAAUAAgB+AKQApwCpAKwArgCxALcAuwD3AZIEDARPBFwEXwSRIBQgGiAeICIgJiAwIDohFiEiIgYiGiIeIkgiYCJl4AH//wAAACAAowCmAKkAqwCuALAAtQC7APcBkgQBBA4EUQReBJAgEyAYIBwgICAmIDAgOSEWISIiBiIaIh4iSCJgImTgAP///+P/v/++/73/vP+7/7r/t/+0/3n+3/xx/HD8b/xu/D7gveC64LnguOC14KzgpN/J377e297I3sXenN6F3oIg6AABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBgAAAQAAAAAAAAABAgAAAAIAAAAAAAAAAAAAAAAAAAABAAADBAUGBwgJCgsMDQ4PEBESExQVFhcYGRobHB0eHyAhIiMkJSYnKCkqKywtLi8wMTIzNDU2Nzg5Ojs8PT4/QEFCQ0RFRkdISUpLTE1OT1BRUlNUVVZXWFlaW1xdXl9gYQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANhqAGJl2m0AaWbgAADlAADja+bnAGwAAAAAAAAAAAAAAABo4nHk4Wdv2wAAAAAAANDR1dbS03AAAAAAAN3eAADZbtTX3AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWACoAWACgAN4BJAEyAUoBYgGAAZQBqAG2AcIB0gIGAhgCVAKQAqwC2gMUAywDbgOmA7gD0gPkA/gEDARABJwEuATuBRwFQgVaBXAFngW4BcYF6AYEBhQGMAZIBm4GjAa+BwgHTgdgB4AHkgeuB8gH4Af4CAoIGggsCEAITAhaCK4I2gkCCSwJWAl6CbIJ0gnmCgYKIAouCmAKgAqmCtAK+gsSC1oLhguqC7wL2AvwDB4MNgxmDHQMpAzQDR4NWA1qDcgOCg4mDjYOdg6WDrAO2A72DwIPHg82D3APlA++D9QQAhBIEFYQbhCQEMQQ8BEaETwRbBGCEZ4RwBH2EgYSKhJCEmwSqBK+EuYTAhMiEz4TWBN+E5ITsBPeE/AUEhRGFGAUeBSeFLYU0hT0FRoVOhVoFZgVvhYSFloWiBaYFroW5hcKFzwXUhd6F5AXrhfMF+AYBhgYGEIYahh8GKoY/hkWGSwZSBleGXgZmhnAGeAaCho4GloakhrAGtgbAhtKG14bdhuWG8Yb7hwUHDQcchyIHJwcrhy8HMoc3hzyHQYdJh1IHWgdfh2cHa4dxB4cHi4eQB58HqIeuh7SHxgfah+MH6YfwB/OH84AAAACAEoAAADMAsgABQAJAAATFQMjAzUTFSM1yCA7H36CAsjM/skBNs39t39/AAIAVQGVAWcCuAADAAcAABMjAzMTIwMzqEESZZxCEWQBlQEj/t0BIwACAA8AAAIlArgAGwAfAAAzIzcjNTM3IzUzNzMHMzczBzMVIwczFSMHIzcjPwEjB6NeJFpoG1loJV4kbiReJFloG1loJF4kbn0bbhvDUJFQxMTExFCRUMPDUJGRAAMADf+cAhoDFAAkACsAMQAAARUeAR0BIzU0JicVFhUUBiMVIzUiJj0BMwYVFBc1LgE1NDY3NRE1DgEVFBYXFT4BNTQBLWR1bDc27YNqMmmFcgF9YH17YjU8O2g4RAMUSAJkUw8HNDEG3CetXnZWVnRrCQUGewv0Dl9YXmMJSP6R0AQ3LS8sgOoCQjRZAAAAAAUAV//hA5YC1QADAA0AFQAfACcAAAkBIwEEMhYVFAYiJjU0NyIVFDMyNTQAMhYVFAYiJjU0NyIVFDMyNTQC2/52TgGM/h+eUlOgVKRMS0wBYJ5SU6BUpExLTALV/QwC9BFhXWRoZWFeJYiBi37++WFdZGhlYV4liIGLfgADACH/8QKWAs4AGgAlAC4AAAEGBxcjJwYjIiY1NDY3JjU0NjMyFhUUBxc2Nyc2NTQmIyIGFRQXBw4BFRQWMzI3AkQJMYyMQlB4X4BaSEdjTUthfm0SB79TKR8gKjsfMzpEMUs6AVRqRaVQX29fRm0hV0ZFWVlFc0OHJjtrMT0hKygeJUp6HT0uL0NNAAEAWQGVAL0CuAADAAATIwMzqj4TZAGVASMAAAABADL/QQEeAs0ACwAAAQ4BFRQXIy4BNTQ3AR09PHpcSUeQAs1004Pn23fKf/7OAAAB//f/QQDjAs0ACwAAExQGByM2NTQmJzMW40dJXHo8PVuQAQF/ynfb54PTdM4AAAABABIBmgFgAtIADgAAAQcXBycHJzcnNxcnMwc3AWBxRTVHRTdFbxZvAUUCbwJGJl4oY2MoXiZAKnZ2KgABACoAAAIvAgMACwAAMzUjNTM1MxUzFSMV+c/PZtDQ0l/S0l/SAAAAAQBH/2MAzwCHAAkAADcVFAYHNTY3IzXPPEw+A0GHZk5fETwTTocAAAEAMADeAVUBSAADAAABFSE1AVX+2wFIamoAAAABAEcAAADPAIcAAwAANxUjNc+Ih4eHAAAB/+7/7wFyAtkAAwAACQEjAQFy/uFlASEC2f0WAuoAAAIAJP/yAggCwgAJACIAAAEyERQGIyIRNDYXIg4EFRQWMzI+BTU0LgQBFPR6dvR6dx4sGxAHAj1DGikaEgkFAQEGERsuAsL+la+2AWexuGAXLy9ILySHehUeMik9IRoiJUsuMhkAAAAAAQBRAAABeQLAAAcAAAERIxEjNTI3AXl6rrYWAsD9QAHkVIgAAQAXAAAB9gLDACkAACUVIT4ENz4GNTQmIyIOAwcjNTQ2MzIWFRQOAwcGBwH1/iIBGB89MSsDNQwqDRcIPTQeLBkQBQFvf2xmfBgbQiArfRllZS9ONzklHQIjCSEUIiMUNz8THi8qHBJxhXNfJkQqOBYdUTwAAAAAAQAb//ECBgLDACoAABM+ATMyFhUUBgceARUUBiMiJj0BMxYzMjY1NCYjIgc1MzI+AjU0JiMiBywDemdheDUtO0SKbm2GbgWDOkROPhMRCh8sLRg6MXAFAdtsfGhUM00PD1c/ZH5+aA+TQzo9OAFWBxMrIC44igAAAgAZAAACCgLCAAoADQAAARUjFSMnITUBMxEjEQMCClluAf7XASxsbc0BBmCmpnEBq/5EAS/+0QABABz/8wIDArgAHAAAARUhBzYzMhYVFAYjIiYnMx4BMzI2NTQmIyIHJxMB3f7pIC9VYXiMbmiBBHEERjU+REY+SypkQwK4Y7QyfmdvjHNhNkBPSEZNPwMBeQAAAAIAJP/yAgsCxAAbACcAAAEjJiMiDgUHNjMyFhUUBiMiJjU0NjMyFgciBhUUFjMyNjU0JgH7bhJYGSocFgsLAgM6ZmF3hWd5gop6WXDVOEJFODdDRAIKYBQaMSE+GBxWgGdrirapr8Ri701AQ1JQQkFPAAAAAQAlAAACAgK4AAoAAAEVBgIHIzYSNyE1AgJtjAZ9BJ5p/pQCuGBt/rOejgFfYmkAAwAg//QCDALFABYAIAAsAAATLgE1NDYzMhYVFAceARUUBiMiJjU0NhMiBhQWMjY1NCYDIgYVFBYzMjY1NCagLzV7Yl54Y0BAiG9uh0O1ND0+ZDw7NTpISD48REgBeRFNNFJoZ1BrKhZQQ2N5dmBBWwEDN1w4Ny8uN/7jRTc8RkM8OkUAAgAe//ICBALFABsAJgAANzMeATMyNwYjIiY1NDYzMh4DFRQOAiMiJhMiBhUUFjI2NTQmLG4EOjB/CzljXnqGaDlZNiMNGTdqSFl52DZBQm5ERK4rNvVZgWVriypDXVwzRX1zRWoCCVFCQUxOP0NQAAIARwAAAM8B/wADAAcAADcVIzUTFSM1z4iIiIeHhwF4h4cAAAIAR/9jAM8B/wADAA0AABMVIzUTFRQGBzU2NyM1z4iIPEw+A0EB/4eH/ohmTl8RPBNOhwABACoABwIvAfsABgAANzUlFQ0BFSoCBf58AYTQZMdqj49sAAACACoAZgIvAZ0AAwAHAAATNSEVBTUhFSoCBf37AgUBPWBg12BgAAAAAQAqAAcCLwH7AAYAACUFNS0BNQUCL/37AYT+fAIF0Mlsj49qxwAAAAIALAAAAfoC1gADACMAADM1MxUnNDY3PgY1NCYjIgcjPgEzMhYVFA4CBw4BFdCBdhsqBB8KGAkNBToudQRzBXhxZXsOJBwfMhR/f8VBUScEGwoZEBkZDiw4jm+BbVkhNC4cGisnQAAAAgAd/+8DAwLZADQAQgAAJRcOASMiJjU0NjMyFhUUBiMiJjU0NwYjIiY1NDYzMhc3MwcGFRQWMzI2NTQmIyIGFRQWMzIDNCYjIg4BFRQWMzI+AQK3HE6QVKPh6aqVvn1TJS4DMlk9S3lQVR0PUkEMFhQyUp5+lsi9lI9GJBwlPB0jHyQ8HIEmOTPJoqPcp4RpnighCA5fVURhkUc32ygVExWBUG2IwJCJrwGUHSZFVCMpMFFfAAAAAAL/+AAAAqMCyQAHAAoAAAkBIychByMBEwsBAZABE4ZE/uZGgQETrWpvAsn9N729Asn+UgEs/tQAAwBKAAAClgLIAA4AFwAiAAATITIWFRQGBx4BFRQGIyETFTMyNjU0JiMDFTMyNjU0LgIjSgFFcHc4Lj5IfWT+lXqqSERHQa67SFIZLzIiAshhUjNREg9aRF50AmPELTU8Jv7i3zA/Iy8WCAAAAQAq/+8CrQLYABwAAAEOASMiJjU0PgEzMhYXIy4BIyIOARUUHgIzMjcCrQqnhZe2TpxpcagRfA1eRUdjKRgwUzefFwEPg53MqWanZ312QElQdUU0XE0utgAAAAACAEsAAAKsAsgADAAVAAATITIWFxYVFAcOASMhExEzMjY1NCYjSwEPSnAvaWQsZ1T+6nyTdWBscQLIHypesb1kLCMCXv4LiHlzgQAAAQBKAAACUQLIAAsAAAEVIRUhFSEVIRUhEQJL/nsBaf6XAYv9+QLIab1l0msCyAAAAQBLAAACOALIAAkAAAEVIRUhFSERIxECOP6RAUL+vn4CyGrCZf7JAsgAAAABACr/7wK8AtcAHQAAAREjJwYjIiY1NDYzMhYXIy4BIyIGFRQWMzI2NSM1ArxQE1WJlru8oHStDHkLYUlndndqXWXAAX3+g1VmzKSh14JwQEmQfX6PdFVgAAAAAAEASQAAAokCyAALAAABESMRIREjETMRIRECiX3+un19AUYCyP04AUD+wALI/uUBGwAAAAABAEwAAADKAsgAAwAAExEjEcp+Asj9OALIAAAAAQAZ/+8B1gLIABQAAAERFAYjIiY9ATMVFBYzMj4DNREB1m9seWl3LDsbJhQLAgLI/gtwdHp2Gyc9QREXKiEcAeQAAAABAEoAAAKxAsgACwAACQIjAwcVIxEzEQECn/7jAS+b6mZ8fAE7Asj+5P5UAVVm7wLI/r0BQwAAAAEASgAAAjICyAAFAAAlFSERMxECMv4YfmxsAsj9pAAAAQBLAAADLwLIAAwAAAERIxEDIwMRIxEzGwEDL3fGZst2r8fAAsj9OAIl/dsCJf3bAsj90wItAAABAEkAAAKMAsgACQAAAREjAREjETMBEQKMgf60doMBSALI/TgCDP30Asj98wINAAACACb/7wLSAtkACgAVAAABMhYQBiMiJjU0NhciBhUUFjMyNjQmAX6Xvb6Ymb25nWJ2dWVhdXUC2c/+tM/Op6LTaZF5fJKT9JEAAAAAAgBNAAACegLIAAoAEQAAEyEyFhUUBisBESMTFTMyNTQjTQE1c4V8a8l9fa6IkwLIbWxmd/7uAmDpdXQAAgAm/74C0QLXABAAIAAAJQcnBiMiJjU0NjMyFhUUBgcnNjU0JiMiBhUUFjMyNyc3Ask9akFol7y/mJa+NTBYQHZjYnV2YyomSTwCRFopzaal0M+jVZAuTVF0eZGReXyTET5EAAIASgAAAqUCyAAoADUAABMhMhYVFAYHHgQXHggXIy4INS4BKwERIxMVMzI+AjU0LgIjSgFRaoY+OBomFQ4FAgEDAQMCBQQGCAWGAwUEAgMBAgECBT9Ypnx8pSQyMxsYLS8gAshfZ0BbFAYYHCwhGwcoDSANGQ0RDAUECw0LEwwYDB4GV0H+2gJi3wgVMCUiLRYIAAABACD/8AJnAtYAMAAAASMmIyIGFRQWFxYXFhcWFRQOAyMiJjUzFBYzMjY1NC4BJyYnJicmJzQ1NDYzMhYCS3cLkEBINVsYDXcrXyA2SlArhqZ7ZlJIUSsyPgcEhSpXBo94dJIB9n01LisgFwcDHhgzbC9MMyIPgHxOSzs1IisSEAIBIhYtXgcHX3FuAAEABwAAAkoCyAAHAAABFSMRIxEjNQJK433jAshs/aQCXGwAAAEARf/yAo0CyAARAAABERAhIiY1ETMRFDMyPgI1EQKN/t6Xj32rNEMgDALI/kz+3pCUAbL+NaQcOkMyAaQAAAAB//sAAAJpAsgABgAAAzMbATMDIwWDtLh/9IsCyP3NAjP9OAABAAgAAAOsAsgADAAAEzMbATMbATMDIwsBIwh/gpJ/jYZ/xX+Qk4ECyP3iAh794gIe/TgCI/3dAAH/+gAAAokCyAALAAAjEwMzFzczAxMjCwEG/uyVoqmM7P2YsrUBcQFX/Pz+qf6PARD+8AAB//sAAAKPAsgACAAACQERIxEBMxsBAo/+9Hv+85C9uwLI/lP+5QEbAa3+xQE7AAABABMAAAJcAsgACQAAARUBIRUhNQEhNQJQ/mEBq/23AZz+ggLIY/4HbGcB9WwAAAABAEf/TAEnAtAABwAAARUjETMVIxEBJ3Z24ALQWf0uWQOEAAABAAP/7wFfAtkAAwAABQEzAQED/wBcAQARAur9FgAAAAEAAf9MAOEC0AAHAAATMxEjNTMRIwHg4HZ2AtD8fFkC0gAAAAEAUAEPAggCuAAGAAAbATMTIwsBUK9ar2d3cwEPAan+VwEq/tYAAAABAAD/gwH0/7UAAwAAFTUhFQH0fTIyAAAB/9wCSAC9AtcAAwAAExcjJ2JbU44C14+PAAAAAgAh//MCIgIUACkAPAAAEzYzMhYVERQWMzI3FQYjIicGIyImNTQ+Bzc+ATc2NTQjIgYHFw4DBw4EFRQWMzI3NjU3EtBhcwsQDA4sHkkLQXRQXgoNHRMrFTQRGz0sCAdqODQH3A0iFS0HFRgjEw4xLEwpFwFlr0xQ/voWEAJQCz4+U0cWJhwYEA4HCAMDCAsLCB1OKjJiBwsDBgEDBQwRHRQlKCkXQgAAAgA9//ICOwLIAA4AGgAAExE2MzIWFRQGIyInFSMREyYGFRQWMzI2NTQmrjlwZ32AanU0a/1DTU1DQE5NAsj++VCSeX2XVEYCyP7uAWFVU2BjU1JgAAAAAAEAJf/zAhACFAAYAAAlDgEjIiY1NDYzMhYXIy4BIyIGFBYzMjY3AhAMgGF0iot2Y3kKcQo8LkJMSUEzQQnDX3GTd4CXZFkxNGOsYD05AAAAAgAn//ICJQLIAA4AGAAAAREjNQYjIiY1NDYzMhcRAyIGFRQWMjY0JgIlazF0bYF/a203j0FLTYZLTQLI/ThHVZR9fJNRAQf+7l9SVWJgql4AAAAAAgAi/+8CEQITABQAGgAAJQ4BIyImNTQ2MzIWHQEhHgEzMjY/AS4BIgYHAgoTf1h1iY1tcYT+gwJKQi87EQIFR3BFCKFUXpd2eZ6bhgxOVS0xkUFLSEQAAAEACgAAATwCzAAVAAABFSYjIgYdATMVIxEjESM1MzU0NjMyATwhESMYYmFxVVVGUyICyVgDGSUyU/5PAbFTKVFOAAAAAgAk/zcCFQISABkAJQAAAREUBiMiJzMWMzI2PQEGIyImNTQ2MzIWFzUHIgYVFBYzMjY1NCYCFXGH1BNyEGhHQThsZ3l+aDdKII1ASUs+QEpJAgT+OIWAnU1IUD1Xi3Z5kyktSE5cUk5cX1FPWQAAAAEAPQAAAgMCyAASAAATETYzMhYVESMRNCYjIgYVESMRrjlqVF5zKTtCPHECyP71VFtY/qIBOTs+Vkf+6wLIAAACAD8AAACxAssAAwAHAAATFSM1FxEjEbFycnICy3Bwx/38AgQAAAAAAv/t/zoAtQLMAA0AEQAAExEUBiMiJzUWMzI2NRE3FSM1tUNVDyEaASAbcnICBP3hW1ADXQISHQI9yHFxAAAAAAEAPQAAAhgCyAALAAABBxMjJwcVIxEzETcCBsbYi51Eb2/OAgS9/rn5QLkCyP5vzQAAAAABAEAAAACxAsgAAwAAExEjEbFxAsj9OALIAAAAAQA9AAADKwISACAAABMVNjMyFhc2MzIWFREjETQmIyIGFREjETQmIyIGFREjEalAYjNLEj5pSWByJjY3OnIhNDo8cgIESVcuKlhXTf6SAT03PkU+/tEBQzc4Sz7+1wIEAAAAAAEAPQAAAgMCEgATAAATFTYzMhYVESMRNC4CIyIVESMRqT5tWFdyBhMqIX5yAgRMWmBa/qgBLB8pKhWd/uoCBAACACT/8AItAhMACwAWAAABMhYVFAYjIiY1NDYWIgYVFBYzMjY1NAErdoyLd3mOj7qITk5FQ00CE5R9fpSUfn2UWmJVV2JjV1UAAAAAAgA+/0ECPAITAA4AGgAAExU2MzIWFRQGIyInESMRFyIGFRQWMzI2NTQmqTR0a4B9aG46cfxDTE1EQUxNAgRFVJZ9epNR/v0Cw01gVVRgYFJUYwAAAgAn/0ECJQITAA4AGgAAAREjEQYjIiY1NDYzMhc1ByIGFRQWMzI2NTQmAiVwPWxpfH9tcjWUQExMQkRMTQIE/T0BBFKRfH+UU0RNY1VSX2FWVF4AAQAyAAABYAIQAAwAAAEVJiMiHQEjETMVNjMBYB4KlXFrN3YCDm0DweMCBGdzAAAAAQAf//EB6AITADIAAAEjJiMiBhUUHgcXHgQVFAYjIiYnMxYzMjY1NC4CJyYnJicmNTQ2MzIWAdVtCmYsMAMJBxILGg8iCScjQyAbemdudgRtCXQyPQ8iHxoLBm4eR3BjX3kBblIgHAkOCwgIBQcEBwIJCRsdMyFOXFxYYSkiERgRCQYDARsPIk9JU1IAAAAAAQAI//sBOAKfAB4AAAEVIxEUHgIzMjcVBiMiLgQ0NTQ9ASM1MzUzFQE4aAIKGRYcESIrHi0eFAsFVlZyAgRT/vAYExcIAloECQwdEzAZHw0G9lObmwAAAAEAPP/yAgECBAAVAAABESM1BiMiJjURMxEUHgMzMjY1EQIBa0FpVVtyAgsVJxxAPAIE/fxNW2FbAVb+2RshKRYQW0YBEQAAAAEACP//Af0CBAAGAAATMxsBMwMjCHyEf3a5gAIE/nMBjf37AAEADAAAAv0CBAAMAAATMxsBMxsBMwMjCwEjDHlmYXNfa3SjdWFgeAIE/n0Bg/59AYP9/AF//oEAAQADAAACFAIEAAsAABMnMxc3MwcTIycHI8azimxxhK/FiYN/hgEP9Z+f7/7rvr4AAQAD/zsCAwIEAB0AAAEDDgkjIic1FjMyPgU3AzMbAQIDvwMQBhEKFBEZGiETIC8kGAwUEAwLBgoBxn2KggIE/gYHLRAoECAOFQkHBmAHBxEPGw8gBAH1/oQBfAABABYAAAHdAgQACQAAARUBIRUhNQEhNQHO/twBM/45ASD+9AIEUP6oXFcBU1oAAAAB/+j/TAFAAtAAHgAAAz4BPQE0NjcVDgEdARQGBx4BHQEUFhcVLgE9ATQmJxhFO2lvPzc5UlU2NkBzZTJOASwLOT1MdF4FPQZCRjpXXAoNWFk8QUUFPQZadTtKPA0AAAABAD3/KgChAxIAAwAAFxEzET1k1gPo/BgAAAAAAf/o/0wBQALQAB4AACUOAR0BFAYHNT4BPQE0NjcuAT0BNCYnNR4BHQEUFhcBQE4yZXNANjZVUjk3P29pO0XvDTxKO3VaBj0FRUE8WVgNClxXOkZCBj0FXnRMPTkLAAAAAQAhAK8CNwFUABwAAAEOASMiJy4DIyIGByM+ATMyFx4FMzI3AjcISj0hZQcsHCMLGiUEQQdGQR5pCiMPGA8TCTUMAVRPVCADDwoJJyBGXiIDDAUIAwJEAAEAIf/yAioC0QA5AAATMxUjFRYVFAYHNjMyFxYzMjcXBiMiJyYjIgcnNjU0JyM1My4BNTQ2MzIWFSMmIyIGFRQeBtqSdgwuNjcuISszFzcnMzdgIFM5Jio9Nm0XWToQGoVrc39xBXw0QwMDCAQMAw4Bfz8BJCEqSywZDA8nVTcYESdRSl4jMD8VVRtbcn5xjUAxCBIOFQoXBhoAAAIAIgBmAgoCTgAbACMAAD8BJjU0Nyc3FzYzMhc3FwcWFRQHFwcnBiMiJwcSIgYUFjI2NCJCJSVCOkIxRz47QTpCJSVCOkIyRUM2Qu9qS0tqS6BCPDxCNkI6QiUlQjpCMUg9OkI6QiUlQgF0S2pLS2oAAAAAAgA9/6cAoQKVAAMABwAAFzUzFQM1MxU9ZGRkWfr6AfT6+gAAAgAZ/0ICEwLUADYAQgAAASMuASMiBhUUHgYXFhcWFRQGBxYVFAYjIiYnMxYzMjY1NCYnLgI1NDY3JjU0NjMyFgUOARUUHwE+ATU0JwHfaQMwKiYuBgcSDiAWLg9XGzw2MTdxWGFwAmsLXicxSnovOC85MCxuV1lr/t4cIzu1GyM4Ah0uMCcgChIOEQsTDBkIMBczRDFOFCxHSl5mWWQpISY3QRgoSS4zTg4tOUhbZNsILRsuIGYJLRksIAADABv/7wMFAtkABwAPACgAABIgFhAGICYQJCAGEBYgNhAHDgEjIiY1NDYzMhYXIy4BIyIGFRQWMzI39gE029v+zNsB+/70vr4BDL6LB2NFWXVvVkpoBEwINyk1QEI4UhMC2dv+zNvbATSqvv70vr4BDMpBVX1eYHxYQyowVERIVVUAAAACADIAVwGSAbkABgANAAABFQcXFSc1JxUHFxUnNQGSX1+bKGFhnQG5aEhKZ3luemZJS2h8bAAAAAEAKgBmAi8BnQAFAAATNSERIzUqAgViAT1g/snXAAAABAANAWQBggLZAAgAEAAkACsAABIyFhUWBiImNDYiBhQWMjY0JzMyFRQHHgEXFBcjJjUuASsBFSM3MzI1NCsBeppuAW+abfqAWlqAWudJWyUTDgEFLgQBEh0WLi4ZLi4ZAtltTU1ubppNWoBbW4AnPCQNBx0gDw0MEB8STXEcGwACACcBgAFpAsIABwARAAASMhYUBiImNDYiBhUUFjI2NTSFhl5ehl7CQi4uQi4Cwl6GXl6GDC4hIC8vICEAAAAAAgAq//ACLwITAAsADwAANzUjNTM1MxUzFSMVBTUhFfnPz2bQ0P7LAgVznmCiomCeg19fAAEAOP9BAgcCBAAZAAAXETMVFBcWMzI+Az0BMxEjNQ4BIyImJxU4cg8YSCEvGg4EcmEdQTEsNwq/AsPlaidCHCg9MiDl/fxHKigmEuwAAAAAAQAR/0oCOQLIAA8AAAEjESMRIxEjES4BNTQ2MyECOTZdb15eaox4ASQCe/zPAzH8zwGvB3dgb4IAAAAAAQBHAN8AzwFmAAMAABMVIzXPiAFmh4cAAgA9AFgBnQG6AAYADQAAARcVBzU3LwEXFQc1NycBAJ2dYGDDmppfXwG6fWx5ZkhMZ3pteGVISgADACoACQIvAfoAAwAHAAsAADc1IRUFNTMVAzUzFSoCBf7CdnZ20l9fyYKCAW+CggABAAD/VwH1AssAJQAAAQcjAw4BIyInNxYzMj4GNxMjNzM3PgEzMhcHJiMiBg8BAbgPZT4UT2gOLQ8QFw4YDw4HCAMGAT5cD1wUEVhYHCURFRMnJAsUAbZQ/rZuVwNZAQYGEggcCCQEAUJQbFtOA1kCJTNjAAMASgAAAlEDcQALAA8AEwAAARUhFSEVIRUhFSERJRUjNSMVIzUCS/57AWn+lwGL/fkBmm9YcALIab1l0msCyKlsbGxsAAAAAAEACP+HAvACyAAcAAAlFAYjIic1MjY1NCYjIgYdASMRIzUhFSMVNjMyFgLwjWcKGEJXSkdDTH3OAkL3OGp1hqB6nwJfZlVWX2BVowJcbGzzUZsAAAIATAAAAi8DhAAFAAkAADMjESEVIRMHIzfJfQHj/prmh1JVAshsASiPjwAAAQAr/+8CqgLYABwAACUOASMiJjU0PgEzMhYXIy4BIyIGByEVIR4BMzI3AqoSpHyXtk6caW6lFX0QXEFZZw4BLf7QCGhgjyLvdYvMqWanZ3ZwOkJzWWVigpYAAAABACD/8AJnAtYAMAAAASMmIyIGFRQWFxYXFhcWFRQOAyMiJjUzFBYzMjY1NC4BJyYnJicmJzQ1NDYzMhYCS3cLkEBINVsYDXcrXyA2SlArhqZ7ZlJIUSsyPgcEhSpXBo94dJIB9n01LisgFwcDHhgzbC9MMyIPgHxOSzs1IisSEAIBIhYtXgcHX3FuAAEATAAAAMoCyAADAAATESMRyn4CyP04AsgAAAAD/+8AAAEmA3AAAwAHAAsAABMRIxE3FSM1IxUjNcp+2m9YcALI/TgCyKhtbW1tAAABABn/7wHWAsgAFAAAAREUBiMiJj0BMxUUFjMyPgM1EQHWb2x5aXcsOxsmFAsCAsj+C3B0enYbJz1BERcqIRwB5AAAAAIACP/zA+oCyAAYACAAACUUBiMhESMDDgEjIic1FjI+ATcTIREzMhYHNCYrARUzMgPqf3T+8soNBmdSJCcUOiQcAw4Bv5F1fn1CO4qMe91qcwJc/q2OiA1gCBxhVgGd/vBybDhA7AAAAgBJAAAD6gLIABIAGgAAASERIxEzESERMxEzMhYVFAYjISU0JisBFTMyAeL+5H19ARx9mHV+f3T+6wGLQjuRk3sBUv6uAsj+8QEP/vByaWpz2jhA7AAAAAEACAAAAuYCyAAbAAABMh4DHQEjNTQuAyMiBxEjESM1IRUjFTYB7D5fMyAKfQIQHDopQUR9zgJC914Buh8tPjMc4bsYHC4aFAv+wAJcbGywDgAAAAIASgAAArEDhAALAA8AAAkCIwMHFSMRMxEBJwcjNwKf/uMBL5vqZnx8ATsWh1JVAsj+5P5UAVVm7wLI/r0BQ7yPjwAAAv/7/+8CaAN8ABEAGwAANwMzGwEzAQ4BIyInNRYzMjY3Ew4BIiYnMxYyN/H2iqywh/7rK2I+LCgdMyAsIOkIUJhQCDoTrhPIAgD+ggF+/clYShJpEjM8ArVIRUVITEwAAQBJ/08CiQLIAAsAACURMxEjFSM1IxEzEQIMfeJ94X1sAlz9OLGxAsj9pAAC//gAAAKjAskABwAKAAAJASMnIQcjARMLAQGQAROGRP7mRoEBE61qbwLJ/Te9vQLJ/lIBLP7UAAIATAAAApECyAAMABQAACUUBiMhESEVIRUzMhYHNCYrARUzMgKRf3T+rgIM/nHVdX59QjvO0HvdanMCyGykcmw4QOwAAwBKAAAClgLIAA4AFwAiAAATITIWFRQGBx4BFRQGIyETFTMyNjU0JiMDFTMyNjU0LgIjSgFFcHc4Lj5IfWT+lXqqSERHQa67SFIZLzIiAshhUjNREg9aRF50AmPELTU8Jv7i3zA/Iy8WCAAAAQBMAAACLwLIAAUAADMjESEVIcl9AeP+mgLIbAAAAAACAAX/TwLHAsgADgAVAAAFIzUhFSMRMzYSPQEhETMjESMVFAYHAsd5/jB5RSk0AdBQzdkvIrGxsQEdSAEUkm79pAHwK4H/RQABAEoAAAJRAsgACwAAARUhFSEVIRUhFSERAkv+ewFp/pcBi/35AshpvWXSawLIAAAB//kAAAQaAsgAEwAAAQMjCQEzAREzEQEzCQEjAwcVIzUBfumcATT+7poBFn0BFpr+7gE0nOlNfQFA/sABmgEu/sABQP7AAUD+0v5mAUBW6uoAAAABACD/8AJcAtkAKgAAJRQOAiMiJjUzFBYzMjY1NCYrATUzMjY1NCYjIgcjPgEzMhYVFAYHFR4BAlwePW5HhqZ7ZlJESEc+V1cxQUI8kAt3BJJ0cZBGLDxLziRJRSyAfE5LQD04OmE+MS81fXJuYWA2WAsDDF8AAAABAEkAAAKJAsgACQAAMxEzEQEzESMRAUl9ATKRff7OAsj93gIi/TgCIv3eAAIASQAAAokDfAAJABMAAAEOASImJzMWMjcBETMRATMRIxEBAg0IUJhQCDoTrhP+dn0BMpF9/s4DfEhFRUhMTPyEAsj93gIi/TgCIv3eAAAAAQBKAAACsQLIAAsAAAkCIwMHFSMRMxEBAp/+4wEvm+pmfHwBOwLI/uT+VAFVZu8CyP69AUMAAAABAAj/8wJ4AsgAEQAAISMRIwMOASMiJzUWMj4BNxMhAnh93A0GZ1IkJxQ6JBwDDgHRAlz+rY6IDWAIHGFWAZ0AAQBLAAADLwLIAAwAAAERIxEDIwMRIxEzGwEDL3fGZst2r8fAAsj9OAIl/dsCJf3bAsj90wItAAABAEkAAAKJAsgACwAAAREjESERIxEzESERAol9/rp9fQFGAsj9OAFA/sACyP7lARsAAAAAAgAm/+8C0gLZAAoAFQAAATIWEAYjIiY1NDYXIgYVFBYzMjY0JgF+l72+mJm9uZ1idnVlYXV1AtnP/rTPzqei02mReXySk/SRAAAAAAEASQAAAokCyAAHAAABESMRIREjEQKJff66fQLI/TgCXP2kAsgAAAACAE0AAAJ6AsgACgARAAATITIWFRQGKwERIxMVMzI1NCNNATVzhXxryX19roiTAshtbGZ3/u4CYOl1dAABACr/7wKtAtgAHAAAAQ4BIyImNTQ+ATMyFhcjLgEjIg4BFRQeAjMyNwKtCqeFl7ZOnGlxqBF8DV5FR2MpGDBTN58XAQ+DncypZqdnfXZASVB1RTRcTS62AAAAAAEABwAAAkoCyAAHAAABFSMRIxEjNQJK433jAshs/aQCXGwAAAH/+//vAmgCyAARAAA3AzMbATMBDgEjIic1FjMyNjfx9oqssIf+6ytiPiwoHTMgLCDIAgD+ggF+/clYShJpEjI8AAAAAwAiAAADBQLIABIAGAAeAAABFAYHFSM1LgI1NDY3NTMVHgEHNCcRPgEFEQYVFBYDBbZ9fU+IXLGCfYSvfbZYXv7Ntl4BZ4OSAlBQAjuBWYKWBEVFBZWCnRP+pQtOWQFbE51STgAAAAAB//oAAAKJAsgACwAAIxMDMxc3MwMTIwsBBv7slaKpjOz9mLK1AXEBV/z8/qn+jwEQ/vAAAQBG/08C1ALIAAsAACUzESM1IREzESERMwKGTnn9630BRn1s/uOxAsj9pAJcAAAAAQAyAAACZALIABcAAAEGIyIuAz0BMxUUHgMzMjcRMxEjAedzSD5fMyAKfQIQHDopUlV9fQE4FB8tPjMcy6UYHC4aFBEBJP04AAAAAAEASQAAA+gCyAALAAAzETMRIREzESERMxFJfQEUfQEUfQLI/aQCXP2kAlz9OAAAAAEARv9PBDMCyAAPAAAzETMRIREzESERMxEzESM1Rn0BFH0BFH1OeQLI/aQCXP2kAlz9pP7jsQAAAgAIAAADDALIAAwAFAAAJRQGIyERIzUhETMyFgc0JisBFTMyAwx/dP7F1gFTvnV+fUI7t7l73WpzAlxs/vBybDhA7AADAEwAAAM3AsgACgASABYAACUUBiMhETMRMzIWBzQmKwEVMzITMxEjAmZ/dP7Zfap1fn1CO6Ole9F9fd1qcwLI/vBybDhA7AJi/TgAAgBMAAACegLIAAoAEgAAJRQGIyERMxEzMhYHNCYrARUzMgJ6f3T+xX2+dX59Qju3uXvdanMCyP7wcmw4QOwAAAEAKf/vAqgC2AAcAAABFAYjIiYnMxYzMjY3ITUhLgEjIgYHIz4BMzIeAQKotpd8pBJ+Io9gaAj+0AEtDmdZQVwQfRWlbmmcTgFkqcyLdZaCYmVZc0I6cHZnpwAAAgBJ/+8D1ALZABEAHQAAATIWEAYjIiYnIxEjETMRMz4BFyIGFRQWMzI2NTQmAo2OubqPibUKfX19gRWtglpxcltZcG8C2dD+ttC7mP6+Asj+5YamaZJ4e5OUeXqRAAAAAv/zAAACZALIAA0AFQAAISMRIwMjEy4BNTQ2MyEDNSMiBhUUMwJkfY7KnNtYQnxwAUR9ukA8egEm/toBMhtqTFpr/r3dMzdzAAAAAAIAIf/zAiICFAApADwAABM2MzIWFREUFjMyNxUGIyInBiMiJjU0Pgc3PgE3NjU0IyIGBxcOAwcOBBUUFjMyNzY1NxLQYXMLEAwOLB5JC0F0UF4KDR0TKxU0ERs9LAgHajg0B9wNIhUtBxUYIxMOMSxMKRcBZa9MUP76FhACUAs+PlNHFiYcGBAOBwgDAwgLCwgdTioyYgcLAwYBAwUMER0UJSgpF0IAAAIAL//yAiwC2wAoADEAACUUBiMiJyY1NDc+ATc+BjczDgkHBgczPgEzMhYHNCYiBhQWMjYCLIhxrjwaQSJiSwkfDRUJDAYDcgMLDBcPIBIoEy8KiisDIVhIZIZyTX5NTX5N/HmRjzxny2Q0MwUBAgEDAwUIBRIeFhIMCgUFAgMBC7c1NZJ3T2BfoGBgAAAAAAMAPAAAAgkCBAAOABYAHQAAJRQGIyERITIWFRQGBxUWByMVMzI1NCYnIxUzMjU0AgljW/7xAR1IUSQmYb6dnU0oNI6RQpJGTAIEQjwpMhICGRqORiImync+OQAAAQA8AAABpQIEAAUAAAEjESMRIQGl93IBaQGq/lYCBAACAAf/XAJOAgQADQAUAAAFIzUhFSM1MzY9ASERMyMRIxUUBgcCTmz+kWxBPQGERbWnIhOkpKT+j+E6/lYBUiNRsS0AAAIAIv/vAhECEwAUABoAACUOASMiJjU0NjMyFh0BIR4BMzI2PwEuASIGBwIKE39YdYmNbXGE/oMCSkIvOxECBUdwRQihVF6Xdnmem4YMTlUtMZFBS0hEAAAB//cAAAMTAgQAFQAAISMnBxUjNScHIxMnMxczNTMVMzczBwMTiZ4wbjCeid7FirEDbgOxisXgNqqqNuABKNza2tra3AAAAAABAB3/8gHiAhMAIwAAJRQGIyImJzMWMzI2NTQrATUzMjU0IyIHIzYzMhYVFAYHFR4BAeKDWW53BHMMaTE6ZUAuZ15SEXMP0ldtMSIpO5lPWF1SVykkTFREQU2kREcqPAcCCEEAAQA8AAACAgIEAAsAADMjETMRMxMzESMRI8yQcgPBkHIDAgT+iAF4/fwBeAACADwAAAICAtkACQAVAAABDgEiJiczFjI3AyMRMxEzEzMRIxEjAcMIUJhQCDoTrhO9kHIDwZByAwLZSEVFSExM/ScCBP6IAXj9/AF4AAAAAAEAPAAAAh4CBAALAAAhIycHFSMRMxU3MwcCHoqiRHJyzovJ50egAgTl5c8AAQAN//QCBAIEABAAACEjESMHDgEjIic1FjMyNxMhAgRyngcDUUYrGwofRAQJAX0BquJlbwtZBYABMQAAAQA8AAAChQIEAA8AADMjETMTMxMzESMRIwMjAyOqbpaQAouWbgJ7c3sCAgT+ZgGa/fwBV/6pAVcAAAAAAQA8AAACAgIEAAsAADMjETMVMzUzESM1I65ycuJycuICBMrK/fzgAAIAJP/wAi0CEwALABYAAAEyFhUUBiMiJjU0NhYiBhUUFjMyNjU0ASt2jIt3eY6PuohOTkVDTQITlH1+lJR+fZRaYlVXYmNXVQAAAAABADwAAAICAgQABwAAMyMRIREjESOucgHGcuICBP38AaoAAAACAD7/QQI8AhMADgAaAAATFTYzMhYVFAYjIicRIxEXIgYVFBYzMjY1NCapNHRrgH1objpx/ENMTURBTE0CBEVUln16k1H+/QLDTWBVVGBgUlRjAAABACX/8wIQAhQAGAAAJQ4BIyImNTQ2MzIWFyMuASMiBhQWMzI2NwIQDIBhdIqLdmN5CnEKPC5CTElBM0EJw19xk3eAl2RZMTRjrGA9OQAAAAEABQAAAcsCBAAHAAABIxEjESM1IQHLqnKqAcYBqv5WAapaAAEAA/87AgMCBAAdAAABAw4JIyInNRYzMj4FNwMzGwECA78DEAYRChQRGRohEyAvJBgMFBAMCwYKAcZ9ioICBP4GBy0QKBAgDhUJBwZgBwcRDxsPIAQB9f6EAXwAAwAk/0EDFgLIACMALwA7AAABFA4BIyImJyMVIzUjDgEjIi4BNTQ2MzIWFzM1MxUzPgEzMhYHNCMiBgcVHgEzMjYFNS4BIyIVFBYzMjYDFidiSRxADwNyAw9AHEliJ25dIEMPA3IDD0MgXW5ycR41CgUwIz83/sAKNR5xNz8jMAEKTXlSHRPh4RMdUnlNeo8gFerqFSCPfLMdIPsYIWwz+yAds1JsIQAAAQADAAACFAIEAAsAABMnMxc3MwcTIycHI8azimxxhK/FiYN/hgEP9Z+f7/7rvr4AAQA8/1wCRwIEAAsAACUzFSM1IREzETMRMwICRW7+Y3Liclr+pAIE/lYBqgABACQAAAHhAgQAEAAAJQYjIiY9ATMVFDMyNzUzESMBb1ZSTlVyXkA7cnLbG09LqoJiGcv9/AAAAAEAPAAAAvICBAALAAAzETMRMxEzETMRMxE8crBysHICBP5WAar+VgGq/fwAAQA8/1wDNwIEAA8AADMRMxEzETMRMxEzETMVIzU8crBysHJFbgIE/lYBqv5WAar+Vv6kAAIABgAAAlgCBAALABQAACQUBiMhESM1IRUzMgc0JisBFTMyNgJYXFP+8JMBBZ1UFigkj5ElJfKaWAGqWrumIyqXKQAAAwA3AAACmwIEAAMADQAWAAABMxEjJhQGKwERMxUzMgc0JisBFTMyNgIpcnJHXFP8colUFigke30lJQIE/fzymlgCBLumIyqXKQAAAAIAPAAAAfsCBAAJABIAACQUBiMhETMVMzIHNCYrARUzMjYB+1xT/vBynVQWKCSPkSUl8ppYAgS7piMqlykAAAABACD/8wIIAhQAGgAAJRQGIyImJzMWMzI2NyM1My4BIyIHIz4BMzIWAgiKdFt+EXEZYDpHB8C/Ckg5WBlyDndfdov9d5NmV2NORlBCSVdTXJcAAAACADz/8AL+AhMAEgAdAAABMhYVFAYjIiYnIxUjETMVMz4BFiIGFRQWMzI2NTQCBnKGhnJshwhdcnJfDoWkgEhIQT9HAhOUfX6UgnDiAgTMZnVaYlVXYmNXVQAAAAL/+AAAAfACBAANABQAACEjNSMHIzcuATU0NjMhBzUjIhUUMwHwcmGfhqw/MFhSARFyik1M0NDdFE03REvhikJIAAAABAAi/+8CEQLIAAMABwAcACIAAAEVIzUjFSM1AQ4BIyImNTQ2MzIWHQEhHgEzMjY/AS4BIgYHAbFvWG8BjxN/WHWJjW1xhP6DAkpCLzsRAgVHcEUIAshtbW1t/dlUXpd2eZ6bhgxOVS0xkUFLSEQAAAEAD/9BAgkCyAAgAAAlFAYHNT4BPQE0IyIGHQEjESM1MzUzFTMVIxUzNjMyFhUCCax6U2FjOEdyNDRy4+MCNmpTX2d6pwVjCmpOP3RMPJEBr1XExFWOUl5SAAAAAgA8AAABpQLXAAUACQAAASMRIxEhJwcjNwGl93IBaUOGUlUBqv5WAgTTj48AAAAAAQAl//MCDQIUABoAACUOASMiJjU0NjMyFhcjJiMiBgczFSMeATMyNwINEX5bdIqLdl93DnIZWDlICsTFB0c6YBmwV2aTd4CXXFNXSUJQRk5jAAAAAQAf//EB6AITADIAAAEjJiMiBhUUHgcXHgQVFAYjIiYnMxYzMjY1NC4CJyYnJicmNTQ2MzIWAdVtCmYsMAMJBxILGg8iCScjQyAbemdudgRtCXQyPQ8iHxoLBm4eR3BjX3kBblIgHAkOCwgIBQcEBwIJCRsdMyFOXFxYYSkiERgRCQYDARsPIk9JU1IAAAAAAgA/AAAAsQLLAAMABwAAExUjNRcRIxGxcnJyAstwcMf9/AIEAAAAAAP/3QAAARQCyAADAAcACwAAExEjETcVIzUjFSM1sXLVcFdwAgT9/AIExG1tbW0AAAL/7f86ALUCzAANABEAABMRFAYjIic1FjMyNjURNxUjNbVDVQ8hGgEgG3JyAgT94VtQA10CEh0CPchxcQAAAAACAAr/9AMTAgQAFwAfAAAlFAYrAREjBw4BIyInNRYzMjcTIRUzMhYHNCYrARUzMgMTW1TshwcDUUYqHAofRAQJAWZ5VVtyKCRrbUqgTVMBquJlbwtZBYABMcVTTiImjQACADwAAAMTAgQAEgAaAAAlFAYrATUjFSMRMxUzNTMVMzIWBzQmKwEVMzIDE1tU8sRycsRyf1VbcigkcXNKoE1T5uYCBMTExVNOIiaNAAAAAAEADwAAAgkCyAAaAAAhIzU0IyIGHQEjESM1MzUzFTMVIxUzNjMyFhUCCXJjOEdyNDRy4+MCNmpTX6V0TDyRAa9VxMRVjlJeUgAAAAACADwAAAIeAtcAAwAPAAABByM3ASMnBxUjETMVNzMHAaGGUlUBAIqiRHJyzovJAtePj/0p50egAgTl5c8AAAAAAgAD/zsCAwLZAAkAJwAAAQ4BIiYnMxYyNxcDDgkjIic1FjMyPgU3AzMbAQGtCFCYUAg6E64TkL8DEAcQChQRGRohEyAvJBgMFBAMCwYKAcZ9ioIC2UhFRUhMTNX+BggrEScSHg8VCQcGYAcHEQ8bDyAEAfX+hAF8AAAAAAEAPP9cAgICBAALAAAlETMRIxUjNSMRMxEBkHKrcqlyWgGq/fykpAIE/lYAAQBMAAACLwNlAAcAAAERIREjESE1Ai/+mn0BZgNl/vf9pALInQAAAAEAPAAAAacCngAHAAABFSMRIxEzNQGn+XL5Ap70/lYCBJoAAAEAAADfAfQBRwADAAABFSE1AfT+DAFHaGgAAAABAAAA3wPoAUcAAwAAARUhNQPo/BgBR2hoAAAAAQBDAbUAzALVAAgAABM1NDcVBgczFUOJPgNBAbVumhg7FE2EAAAAAAEASQGoANICyAAIAAATFRQHNTY3IzXSiT4DQQLIbpoYOxRNhAAAAAABAE3/ZQDKAIAACQAANxUUBzU+ATcjNcp9Hx0CPoBkmxw4DS4ogAAAAgA7AbkBfgLUAAkAEwAAEzU0NjcVBhUzFTM1NDY3FQYVMxU7SjQ9PUdKND09Abl7P1cKORdLgHs/Vwo5F0uAAAIAPAGtAX8CyAAJABMAAAEVFAYHNTY1IzUjFRQGBzU2NSM1AX9KND09R0o0PT0CyHs/Vwo5F0uAez9XCjkXS4AAAAAAAgA9/2UBgACAAAkAEwAAJRUUBgc1NjUjNSMVFAYHNTY1IzUBgEo0PT1HSjQ9PYB7P1cKORdLgHs/Vwo5F0uAAAEAIf9gAgsCyAALAAABFSMRIxEjNTM1MxUCC79uvb1uAf9h/cICPmHJyQAAAQAh/2ECCwLIABMAAAEVIxEzFSMVIzUjNTMRIzUzNTMVAgvAwMBsvr6+vmwCBmD+3GDBwWABJGDCwgAAAQBIALIBrAIWAAcAABIyFhQGIiY0sJRoaJRoAhZolGholAAAAwBsAAADfACCAAMABwALAAAzNTMVMzUzFTM1MxVsddh12HaCgoKCgoIAAAAHAE//4QQtAtUAAwAOABkAIgArADMAOAAACQEjAQMyFhUUBiMiNTQ2JTIWFRQGIyI1NDYAMhYUBiImNTQBIhUUFjMyNTQhIhUUMzI1NAAiFRQyApH+O0oBxwZFS0pGk0sBoUZLS0aSS/1FjkpNjEoB80EgIj4BGkFCP/1FgIAC1f0MAvT+c1ZPVVqoVVcBVlFUWqhUWQF6V6RaV1JT/qNxODRxbHFscG0BenNpAAAAAAEAKwBXAMUBuAAGAAATFQcXFSc1xV5emgG4Z0hKaHttAAAAAAEAPQBZANcBuQAGAAATFxUHNTcnPZqaX18BuXpvd2ZISgAAAAQARwAAA+wCuAAKABQAHgAiAAABFAYjIiY0NjMyFgEjAREjETMBETMANCYjIgYUFjMyFyE1IQPsVE9OVVZNTFf+gIT+1neEASp3ASksICErKyEgg/67AUUBF0xSUZRSUv6iAfv+BQK4/gQB/P40UDMyUjG6VQAAAAIAZwFkA08CyAAHABQAABMRIzUhFSMRMxEzFzczESMRAyMDEdpzAStyrGlaWWc/ZzZnAWQBLTc3/tMBZPv7/pwBJf7bASX+2wAAAAACAAoAAAKgArgAAwAGAAAJASEBAyEDAYMBHf1qARGIAX/EArj9SAK4/aMB7QAAAAABAAr/KgIvAxIACAAAAQMjAwcnNxsBAi/UX5wxJYiJrQMS/BgBQhdQP/7fA08AAAADACwAVQLwAa4AGgAkADAAAAE+AjMyFhUUBiMiJicOBCMiJjQ2MzIWFxYzMjY1NCYjIgcmIyIGFRQWMzI+AQGPIC1MJ0daWUg3Wi8HNBUsKhpIW1pGOlZnTz4jLC0kOLxYNyEsLCUaNyIBOCUqJ19MTWE7NAYyDx0KX5hgPHJTLyUnMFhXMSUmLR0dAAIAIQBLAjcBtwAcADkAAAEOASMiJy4DIyIGByM+ATMyFx4FMzI3Fw4BIyInLgMjIgYHIz4BMzIXHgUzMjcCNwhKPSFlBywcIwsaJQRBB0ZBHmkKIw8YDxMJNQxBCEo9IWUHLBwjCxolBEEHRkEeaQojDxgPEwk1DAG3T1QgAw8KCScgRl4iAwwFCAMCRMdPVCADDwoJJyBGXiIDDAUIAwJEAAAAAQAp/88CLgI0ABMAAD8BIzUhNxcHMxUjBzMVIQcnNyM12D3sAR1NVDh/sD3t/uJNVDh+xndfmCttX3dglytsYAAAAAACACb/3gIrAiUABgAKAAATNSUVDQEVBSEVISYCBf5+AYL9+wIF/fsBD2G1ZYB7ZSJgAAAAAgAt/94CMgIlAAYACgAAAQU1LQE1BREVITUCMv37AYL+fgIF/fsBD69le4Bltf7OYGAAAAEAMADeAVUBSAADAAABFSE1AVX+2wFIamoAAAAAABYBDgABAAAAAAAAAPEB5AABAAAAAAABABAC+AABAAAAAAACAAYDFwABAAAAAAADAEMDpgABAAAAAAAEABcEGgABAAAAAAAFAAcEQgABAAAAAAAGABcEegABAAAAAAAHAFEFNgABAAAAAAAIAD8GCAABAAAAAAAQABAGagABAAAAAAARAAYGiQADAAEECQAAAeIAAAADAAEECQABACAC1gADAAEECQACAAwDCQADAAEECQADAIYDHgADAAEECQAEAC4D6gADAAEECQAFAA4EMgADAAEECQAGAC4ESgADAAEECQAHAKIEkgADAAEECQAIAH4FiAADAAEECQAQACAGSAADAAEECQARAAwGewBDAG8AcAB5AHIAaQBnAGgAdABlAGQAIAAoAGMAKQAgADEAOQA4ADEALAAgADEAOQA5ADcAIABiAHkAIABhAG4AZAAgAHQAaABlACAAcAByAG8AcABlAHIAdAB5ACAAbwBmACAATABpAG4AbwB0AHkAcABlAC0ASABlAGwAbAAgAEEARwAgAGEAbgBkAC8AbwByACAAaQB0AHMAIABzAHUAYgBzAGkAZABpAGEAcgBpAGUAcwAuACAAQQBsAGwAIABSAGkAZwBoAHQAcwAgAFIAZQBzAGUAcgB2AGUAZAAuACAAQQBsAGwAIABDAHkAcgBpAGwAbABpAGMAIABjAGgAYQByAGEAYwB0AGUAcgBzACAAZABlAHMAaQBnAG4AZQBkACAAYgB5ACAARABvAHUAYgBsAGUAQQBsAGUAeAAuACAASABlAGwAdgBlAHQAaQBjAGEAIABpAHMAIABhACAAcgBlAGcAaQBzAHQAZQByAGUAZAAgAFQAcgBhAGQAZQBtAGEAcgBrACAAbwBmACAATABpAG4AbwB0AHkAcABlAC0ASABlAGwAbAAgAEEARwAgAGEAbgBkAC8AbwByACAAaQB0AHMAIABzAHUAYgBzAGkAZABpAGEAcgBpAGUAcwAuAABDb3B5cmlnaHRlZCAoYykgMTk4MSwgMTk5NyBieSBhbmQgdGhlIHByb3BlcnR5IG9mIExpbm90eXBlLUhlbGwgQUcgYW5kL29yIGl0cyBzdWJzaWRpYXJpZXMuIEFsbCBSaWdodHMgUmVzZXJ2ZWQuIEFsbCBDeXJpbGxpYyBjaGFyYWN0ZXJzIGRlc2lnbmVkIGJ5IERvdWJsZUFsZXguIEhlbHZldGljYSBpcyBhIHJlZ2lzdGVyZWQgVHJhZGVtYXJrIG9mIExpbm90eXBlLUhlbGwgQUcgYW5kL29yIGl0cyBzdWJzaWRpYXJpZXMuAABIAGUAbAB2AGUAdABpAGMAYQBOAGUAdQBlAEMAeQByAABIZWx2ZXRpY2FOZXVlQ3lyAABNAGUAZABpAHUAbQAATWVkaXVtAABUAHIAYQBuAHMAVAB5AHAAZQAgADMAIABNAEEAQwA7AEgAZQBsAHYAZQB0AGkAYwBhAE4AZQB1AGUAQwB5AHIALQBNAGUAZABpAHUAbQA7ADAAMAAxAC4AMAAwADAAOwA4AC8AMgA5AC8AMAA2ACAAMQAwADoAMwA5ADoANAA3ACAAQQBNAABUcmFuc1R5cGUgMyBNQUM7SGVsdmV0aWNhTmV1ZUN5ci1NZWRpdW07MDAxLjAwMDs4LzI5LzA2IDEwOjM5OjQ3IEFNAABIAGUAbAB2AGUAdABpAGMAYQBOAGUAdQBlAEMAeQByAC0ATQBlAGQAaQB1AG0AAEhlbHZldGljYU5ldWVDeXItTWVkaXVtAAAwADAAMQAuADAAMAAwAAAwMDEuMDAwAABIAGUAbAB2AGUAdABpAGMAYQBOAGUAdQBlAEMAeQByAC0ATQBlAGQAaQB1AG0AAEhlbHZldGljYU5ldWVDeXItTWVkaXVtAABQAGwAZQBhAHMAZQAgAHIAZQBmAGUAcgAgAHQAbwAgAHQAaABlACAAQwBvAHAAeQByAGkAZwBoAHQAIABzAGUAYwB0AGkAbwBuACAAZgBvAHIAIAB0AGgAZQAgAGYAbwBuAHQAIAB0AHIAYQBkAGUAbQBhAHIAawAgAGEAdAB0AHIAaQBiAHUAdABpAG8AbgAgAG4AbwB0AGkAYwBlAHMALgAAUGxlYXNlIHJlZmVyIHRvIHRoZSBDb3B5cmlnaHQgc2VjdGlvbiBmb3IgdGhlIGZvbnQgdHJhZGVtYXJrIGF0dHJpYnV0aW9uIG5vdGljZXMuAABiAHkAIABhAG4AZAAgAHQAaABlACAAcAByAG8AcABlAHIAdAB5ACAAbwBmACAATABpAG4AbwB0AHkAcABlAC0ASABlAGwAbAAgAEEARwAgAGEAbgBkAC8AbwByACAAaQB0AHMAIABzAHUAYgBzAGkAZABpAGEAcgBpAGUAcwAAYnkgYW5kIHRoZSBwcm9wZXJ0eSBvZiBMaW5vdHlwZS1IZWxsIEFHIGFuZC9vciBpdHMgc3Vic2lkaWFyaWVzAABIAGUAbAB2AGUAdABpAGMAYQBOAGUAdQBlAEMAeQByAABIZWx2ZXRpY2FOZXVlQ3lyAABNAGUAZABpAHUAbQAATWVkaXVtAAAAAAIAAAAAAAD/tQAyAAAAAAAAAAAAAAAAAAAAAAAAAAAA6gAAAAEAAgADAAQABQAGAAcACAAJAAoACwAMAA0ADgAPABAAEQASABMAFAAVABYAFwAYABkAGgAbABwAHQAeAB8AIAAhACIAIwAkACUAJgAnACgAKQAqACsALAAtAC4ALwAwADEAMgAzADQANQA2ADcAOAA5ADoAOwA8AD0APgA/AEAAQQBCAEMARABFAEYARwBIAEkASgBLAEwATQBOAE8AUABRAFIAUwBUAFUAVgBXAFgAWQBaAFsAXABdAF4AXwBgAGEAhQC9AOgAhgCLAKkApACKAIMAkwCXAIgAwwCqALgApgECAQMBBAEFAQYBBwEIAQkBCgELAQwBDQEOAQ8BEAERARIBEwEUARUBFgEXARgBGQEaARsBHAEdAR4BHwEgASEBIgEjASQBJQEmAScBKAEpASoBKwEsAS0BLgEvATABMQEyATMBNAE1ATYBNwE4ATkBOgE7ATwBPQE+AT8BQAFBAUIBQwFEAUUBRgFHAUgBSQFKAUsBTAFNAU4BTwFQAVEBUgFTAVQBVQFWAVcBWAFZAVoBWwFcAV0BXgFfALIAswC2ALcAxAC0ALUAxQCCAMIAhwCrAMYAvgC/AWAAjACoAKUAkgCnAI8AlACVAWEBYglhZmlpMTAwMjMJYWZpaTEwMDUxCWFmaWkxMDA1MglhZmlpMTAwNTMJYWZpaTEwMDU0CWFmaWkxMDA1NQlhZmlpMTAwNTYJYWZpaTEwMDU3CWFmaWkxMDA1OAlhZmlpMTAwNTkJYWZpaTEwMDYwCWFmaWkxMDA2MQlhZmlpMTAwNjIJYWZpaTEwMTQ1CWFmaWkxMDAxNwlhZmlpMTAwMTgJYWZpaTEwMDE5CWFmaWkxMDAyMAlhZmlpMTAwMjEJYWZpaTEwMDIyCWFmaWkxMDAyNAlhZmlpMTAwMjUJYWZpaTEwMDI2CWFmaWkxMDAyNwlhZmlpMTAwMjgJYWZpaTEwMDI5CWFmaWkxMDAzMAlhZmlpMTAwMzEJYWZpaTEwMDMyCWFmaWkxMDAzMwlhZmlpMTAwMzQJYWZpaTEwMDM1CWFmaWkxMDAzNglhZmlpMTAwMzcJYWZpaTEwMDM4CWFmaWkxMDAzOQlhZmlpMTAwNDAJYWZpaTEwMDQxCWFmaWkxMDA0MglhZmlpMTAwNDMJYWZpaTEwMDQ0CWFmaWkxMDA0NQlhZmlpMTAwNDYJYWZpaTEwMDQ3CWFmaWkxMDA0OAlhZmlpMTAwNDkJYWZpaTEwMDY1CWFmaWkxMDA2NglhZmlpMTAwNjcJYWZpaTEwMDY4CWFmaWkxMDA2OQlhZmlpMTAwNzAJYWZpaTEwMDcyCWFmaWkxMDA3MwlhZmlpMTAwNzQJYWZpaTEwMDc1CWFmaWkxMDA3NglhZmlpMTAwNzcJYWZpaTEwMDc4CWFmaWkxMDA3OQlhZmlpMTAwODAJYWZpaTEwMDgxCWFmaWkxMDA4MglhZmlpMTAwODMJYWZpaTEwMDg0CWFmaWkxMDA4NQlhZmlpMTAwODYJYWZpaTEwMDg3CWFmaWkxMDA4OAlhZmlpMTAwODkJYWZpaTEwMDkwCWFmaWkxMDA5MQlhZmlpMTAwOTIJYWZpaTEwMDkzCWFmaWkxMDA5NAlhZmlpMTAwOTUJYWZpaTEwMDk2CWFmaWkxMDA5NwlhZmlpMTAwNzEJYWZpaTEwMDk5CWFmaWkxMDEwMAlhZmlpMTAxMDEJYWZpaTEwMTAyCWFmaWkxMDEwMwlhZmlpMTAxMDQJYWZpaTEwMTA1CWFmaWkxMDEwNglhZmlpMTAxMDcJYWZpaTEwMTA4CWFmaWkxMDEwOQlhZmlpMTAxMTAJYWZpaTEwMTkzCWFmaWkxMDA1MAlhZmlpMTAwOTgJYWZpaTYxMzUyC2h5cGhlbm1pbnVzB25ic3BhY2UAAAAB//8AAgABAAAADgAAADAAAAAAAAIABQADAAcAAQAIAAgAAgAJANsAAQDcANwAAgDdAOkAAQAEAAAAAgAAAAEAAAAKAB4ALAABbGF0bgAIAAQAAAAA//8AAQAAAAFmcmFjAAgAAAABAAAAAwAIABIAGgAGAAAAAgAaAEgABAAAAAEAZAAEAAAAAQB4AAMAAAAEABYAHAAiACgAAAABAAAAAQABAAEAEwABAAEAEgABAAEAEwABAAEAEwADAAAAAwAUABoAIAAAAAEAAAACAAEAAQATAAEAAQASAAEAAQATAAEAFgABAAgAAQAEANwABAASABMAEwABAAEAEwABABQAAQAIAAEABAAIAAMAEgATAAEAAQATAAEAAAAKACAAOgABbGF0bgAIAAQAAAAA//8AAgAAAAEAAmNwc3AADmtlcm4AFAAAAAEAAAAAAAEAAQACAAYADgABAAAAAQAQAAIAAAABABwAAQAKAAUABwAOAAIAAQAkAD0AAAABBpgABAAAAD8AiACOALwA3gDsAQYBFAEmAWQBmgHIAgICDAIyAjwCRgJQAl4CdAKGAqQCsgK4AxYDJAMqA0ADUgNAA3QD9gSoBLICXgNAA0AEvATWBNwFBgUMBSoE1gUqBTwEvAVaBXQFngXMBSoF2gS8BewGAgYIBggGAgYaBjwGSgZsBnoAAQCy/8gACwCTAB0Aof/GAKT/0ACn/7MAqv/jAKv/0ACs/9kArv+zALH/swC3/9kAv//GAAgAN/+kADn/wgA6/+cAPP+2AFn/7gBa/+4AXP/uANP/tgADAA//fwAR/38AJP/JAAYAN/+kADn/pAA6/8kAPP+RAFz/2wDT/7YAAwAP/1cAEf9XACT/tgAEADf/7gA5/+4AOv/uADz/2wAPAA//kQAQ/38AEf+RAB3/rQAe/60AJP+kAET/nABG/5EASP+RAFL/kQBV/6QAVv+RAFj/pABa/5EAXP+RAA0AD/9/ABD/yQAR/38AHf/SAB7/0gAk/8kARP/JAEj/yQBMAAoAUv/JAFX/2wBY/9sAXP/uAAsAD/+2ABD/5AAR/7YAHf/uAB7/7gAk/+cARP/bAEj/7gBS/+4AVf/uAFj/7gAOAA//kQAQ/5EAEf+RAB3/pAAe/6QAJP+2AET/pABI/6QATP/3AFL/pABT/6oAVP+YAFj/qgBZ/8kAAgBJ/+4A0wASAAkAD/+kABH/pABG/+4AR//uAEj/7gBRABIAUv/uAFT/7gDl/8kAAgAP/7YAEf+2AAIAD//JABH/yQACAA//pAAR/6QAAwAR/3gAHf+pAB7/qQAFAJL/wACT/+MAl//FANP/swDW/7MABACS/8AAk//jANP/swDW/7MABwBz/8YAfP/GAJL/pACX/8cAsv/mANP/tgDW/7YAAwCL/+gAkv/gAJf/5gABAIv/6AAXAA//eAAQ/5UAEf94ABL/nwAd/6kAHv+pAID/mACE/8cAi/+0AKD/dwCi/4gApP9wAKX/dwCm/4gAqP+IAKv/cACs/4gArf+IAK7/dwCw/4gAs/+IALb/iAC+/4gAAwCO/+4Akf/uAJ3/7gABAIv/7gAFAHX/7gCO/+4Akf/uAJT/4ACd/+4ABACG/+4Ai//uAJL/7gCV/+4ACAAP/1cAEf9XABL/vACA/7YAhP/QAIb/5gCL/8EApP/gACAAD/+RABD/lQAR/5EAEv+fAB3/rQAe/60Adf/uAID/pACL/9wAjv/uAJH/7gCU/+AAnf/uAKD/qACi/7AApf+oAKj/sACq/7AAq/+oAKz/sACt/7AArv+oALD/sACz/6gAuf+wALv/sAC8/7AAvf+oAL7/sAC//6gAwP/IAMP/qAAsAA//fwAQ/9AAEf9/ABL/vAAd/9IAHv/SAHn/nwB6/+AAgP+4AIT/0ACH/+YAi//WAI7/5gCR/+YAlP/gAKD/wACh/8AAov/IAKP/yACk/7gApf/AAKb/yACn/8AAqP/IAKn/0ACq/8gAq/+4AKz/yACt/8gArv/AAK//yACw/8gAsf/AALL/yAC0/8AAtf/IALb/yAC3/+AAuP/IALn/yAC9/8AAvv/IAL//yADI/7gAAgCL/+YAkv/gAAIA0/+zANb/swAGAKT/9ACm//QAq//oALL/9ACz//QAtf/0AAEAq//uAAoAD/+VABD/swAR/5UAEv+8AKD/7gCk/9oApf/uAKv/yQCu/+4Asf/uAAEAEgAdAAcApP/0AKb/9ACr/+4Asv/0ALP/9AC1//QAyP/uAAQApf/0AK7/9ACx//QAvf/0AAcApP/0AKb/9ACr/+gAsv/0ALP/9AC1//QAyP/uAAYApP/0AKb/9ACr/+4Asv/0ALP/9AC1//QACgAP/6kAEP/IABH/qQCg/+4Apf/uAKv/1gCu/+4Asf/uAL3/7gDD/+4ACwAP/6QAEf+kAKD/9ACk/+4Apf/0AKv/3gCu//QAsf/0ALT/9AC9//QAyP/uAAMAq//oALL/9ACz//QABACy/8gAt//gANP/xgDW/8YABQCk//QApv/0AKv/6ACy//QAtf/0AAEAs//gAAQAsv/IALP/0ADT/8YA1v/GAAgAEf94AB3/qQAe/6kAgP+YAIT/xwCg/3cApf93AK7/dwADAKD/7gCl/+4Arv/uAAgAev/QAID/tgCE/8YAi//QAKT/xgCr/8YAyP/GANL/sQADAFb/tgBX/+4A0/+xAAcAev/QAID/tgCE/8YAi//QAKT/xgCr/8YAyP/GAAEAPwAQABIAJAApAC8AMwA1ADcAOQA6ADwASQBVAFkAWgBcAHQAegB7AIAAgQCCAIMAhgCHAIoAjgCQAJEAkgCTAJQAmgCcAJ0AngChAKIAowCkAKUApgCnAKoArgCwALEAsgCzALQAtQC8AL0AvgDBAMgAyQDKAM4AzwDSANMA1QAAAAAAAQAAAADMPaLPAAAAAMEZyfQAAAAAwRnJ9A==';
const DEFAULT_SCALE = 1;
const TEXT_COLOR = '#333333';
const LINE_HEIGHT = 11;
const ORIENTATION_LANDSCAPE = 'l';
const ORIENTATION_PORTRAIT = 'p';
const DEFAULT_FORMAT = 'a4';
const CHECK = 'iVBORw0KGgoAAAANSUhEUgAAAA4AAAAOCAYAAAAfSC3RAAAA5UlEQVQoz53Ruy6EURTF8d8nk6DRiVYiIRGFOA+g8BKi5gW8gkvlCTQovMOUoraimWJQKFwiKoViIhGaj4wxEzN2c7Iv/+y9zuIfUUppVCMCY9jCYWMEaBIXWEvyMTYkNIV7HCV5gmoIaAItvCVZ/KoPc2oTs1jqLjZKKRXWcZ7koWfbJlbRTNLu7lX1QIWbWsdGksdSSgN3mMFckttfYJeWNqaxjw4OcJlkpff+719N0sEyXrGLvbp10k/4DzuSvGC7TsfxjuN+YDXAgivM4zrJwp8bu2KnfluDPBrk4ynO8DwI/ARdo0Nc2KskUgAAAABJRU5ErkJggg==';
const WORKER_URL = '/vendor/pdfjs/pdf-worker.js';
const pdfjsLib = window['pdfjs-dist/build/pdf'];

if (pdfjsLib !== undefined) {
    pdfjsLib.GlobalWorkerOptions.workerSrc = WORKER_URL;
}

const pdfFactory = (render, options = {}, installFont = true) => {
    let pdf = new jsPDF({unit: 'pt', ...options});
    if (installFont) {
        pdf.addFileToVFS('font.ttf', FONT_DATA);
        pdf.addFont('font.ttf', 'PTSans', 'normal');
        pdf.setFont('PTSans');
    }
    pdf.setFontSize(10);
    pdf.setTextColor(TEXT_COLOR);
    return render(pdf).then(() => {
        return pdf.output('blob');
    });
}

const pts = (x) => x * 0.75;

const multiPagesToPdf = (documents, options = {}) => {
    return new Promise((resolve, reject) => {
        let promises = [];
        let canvases = [];
        let opts = {
            width: 700,
            scale: 1.5,
            paddingH: 30,
            paddingV: 30,
            format: 'JPEG',
            ...options,
        }
        documents.forEach(page => {
            page.document.body.className += ' pdf-canvas';
            promises.push(
                html2canvas(page.document.body).then((canvas) => {
                    canvases.push(canvas);
                })
            );
        });

        Promise.all(promises).then(() => {
            return pdfFactory((pdf) => {
                for (let i = 0; i < canvases.length; i++) {
                    if (i > 0) {
                        pdf.addPage(i+1);
                        pdf.setPage(i+1);
                    }
                    pdf.addImage(canvases[i], opts.format, pts(opts.paddingH), pts(opts.paddingV));
                }
                return Promise.resolve();
            }, {'format': 'a4'}, false).then(resolve);
        });
    });
}

const pageToPdf = (document, options = {}) => {
    return new Promise((resolve, reject) => {
        setTimeout(() => {
            let opts = {
                width: 700,
                scale: 1.5,
                paddingH: 30,
                paddingV: 30,
                format: 'JPEG',
                ...options,
            }
            document.body.className += ' pdf-canvas';
            html2canvas(document.body, {
                width: opts.width,
                windowWidth: opts.width,
                scale: opts.scale,
                allowTaint: true,
            }).then((canvas) => {
                let w = canvas.width / opts.scale;
                let h = canvas.height / opts.scale;
                return pdfFactory((pdf) => {
                    pdf.addImage(canvas, opts.format, pts(opts.paddingH), pts(opts.paddingV), pts(w), pts(h));
                    return Promise.resolve();
                }, {
                    'format': [
                        pts(w + 2 * opts.paddingH),
                        pts(h + 2 * opts.paddingV),
                    ]
                }, false).then(resolve);
            }).catch(reject);
        }, 500);
    });
}

class PdfBlank {
    /**
     * Constructor
     *
     * @param {string} url
     * @param container
     * @param blankDefaults
     * @param images
     */
    constructor(url, container, blankDefaults = {}, images = null) {
        if (pdfjsLib === undefined) {
            throw 'PDFjs library not found!';
        }

        this._document = null;
        this._container = container;
        this._ready = false;
        this._blankDefaults = blankDefaults;
        this._pages = [];
        this._images = images;
        this._sketchpads = [];
        this._pageSizes = [];
        fileLoader.get(url).then((blobUrl) => {
            pdfjsLib.getDocument(blobUrl).promise.then((doc) => {
                this._document = doc;
                this.renderDocument().then(() => {
                    this._ready = true;
                    fileLoader.revoke(url);
                    this.setFormData(this._blankDefaults);
                });
            });
        });
    }

    /**
     * Render the document
     */
    renderDocument() {
        let promise = Promise.resolve();
        let doc = this._document;
        let container = this._container;
        let pageViews = this._pages;
        let pageSizes = this._pageSizes;

        for (let i = 1; i <= doc.numPages; i++) {
            promise = promise.then(function (pageNum) {
                return doc.getPage(pageNum).then((pdfPage) => {
                    let pdfPageView = new pdfjsViewer.PDFPageView({
                        container: container,
                        id: pageNum,
                        scale: DEFAULT_SCALE,
                        defaultViewport: pdfPage.getViewport({
                            scale: DEFAULT_SCALE,
                        }),
                        annotationLayerFactory: new pdfjsViewer.DefaultAnnotationLayerFactory(),
                        renderInteractiveForms: true,
                    });
                    pageViews.push(pdfPageView);
                    pdfPageView.setPdfPage(pdfPage);
                    pageSizes[pageNum] = [pdfPageView.width * 0.75, pdfPageView.height * 0.75];
                    return pdfPageView.draw();
                });
            }.bind(null, i));
        }

        promise.then(() => {
            this.getAnnotations((page, index, annotations) => {
                annotations.forEach((annotation) => {
                    if (annotation.fieldType === 'Sig') {
                        let rect = this.normalizeRect([
                            annotation.rect[0],
                            page.pdfPage.view[3] - annotation.rect[1] + page.pdfPage.view[1],
                            annotation.rect[2],
                            page.pdfPage.view[3] - annotation.rect[3] + page.pdfPage.view[1],
                        ]);

                        let annotationLayer = document.querySelector('.annotationLayer');

                        let width = (annotation.rect[2] - annotation.rect[0]) * 1.333333;
                        let height = (annotation.rect[3] - annotation.rect[1]) * 1.33333;
                        let sketchSection = this.createSection(annotation, rect, width, height);

                        let sketchpad = new Sketchpad(sketchSection, {
                            width: width,
                            height: height,
                            line: {
                                color: '#000000',
                                size: 2
                            }
                        })

                        let toolsDiv = this.createToolsDiv(sketchpad);
                        sketchSection.prepend(toolsDiv);
                        annotationLayer.appendChild(sketchSection);

                        this._sketchpads.push(
                            {
                                annotation: annotation,
                                sketchpad: sketchpad
                            }
                        );
                    }
                });
            });
        })

        return promise;
    }

    createSection(annotation, rect, width, height) {
        let sketchSection = document.createElement("section");
        sketchSection.setAttribute("data-annotation-id", annotation.id);
        sketchSection.classList.add('sketchAnnotation');

        sketchSection.style.left = `${rect[0] * 1.3333333}px`;
        sketchSection.style.top = `${rect[1] * 1.33333}px`;
        sketchSection.style.width = `${width}px`;
        sketchSection.style.height = `${height}px`;

        return sketchSection;
    }

    createToolsDiv(sketchpad) {

        let toolsDiv = document.createElement("div");

        toolsDiv.classList.add('sketchpad-tools');

        let undoButton = document.createElement('span');
        undoButton.classList.add('icon-small', 'icon-blue', 'cursor-pointer', 'svg-icon');
        undoButton.title = __('Назад');

        let colorPicker = document.createElement('input');
        colorPicker.style.marginTop = '10px';
        colorPicker.style.width = '20px';
        colorPicker.type = 'color';
        colorPicker.title = __('Цвет');
        colorPicker.style.cursor = 'pointer';

        let redoButton = document.createElement('span');
        redoButton.title = __('Вперёд');
        redoButton.classList.add('icon-small', 'icon-blue', 'cursor-pointer', 'svg-icon');
        redoButton.style.marginTop = '10px';

        let clearButton = document.createElement('span');
        clearButton.title = __('Очистить');
        clearButton.classList.add('icon-small', 'icon-blue', 'cursor-pointer', 'svg-icon');
        clearButton.style.marginTop = '10px';


        let undoSvgElem = document.createElementNS('http://www.w3.org/2000/svg', 'svg'),
            undoUseElem = document.createElementNS('http://www.w3.org/2000/svg', 'use');

        undoUseElem.setAttributeNS('http://www.w3.org/1999/xlink', 'xlink:href', '/svg/spritesheet/sprite.svg#arrow-circle');

        undoSvgElem.style.transform = 'scaleX(-1)';
        undoSvgElem.appendChild(undoUseElem);


        let clearSvgElem = document.createElementNS('http://www.w3.org/2000/svg', 'svg'),
            clearUseElem = document.createElementNS('http://www.w3.org/2000/svg', 'use');

        clearUseElem.setAttributeNS('http://www.w3.org/1999/xlink', 'xlink:href', '/svg/spritesheet/sprite.svg#delete');

        clearSvgElem.appendChild(clearUseElem);

        let redoSvgElem = document.createElementNS('http://www.w3.org/2000/svg', 'svg'),
            redoUseElem = document.createElementNS('http://www.w3.org/2000/svg', 'use');

        redoUseElem.setAttributeNS('http://www.w3.org/1999/xlink', 'xlink:href', '/svg/spritesheet/sprite.svg#arrow-circle');

        redoSvgElem.appendChild(redoUseElem);

        /*
        * Buttons inner
        * */
        redoButton.appendChild(redoSvgElem);
        undoButton.appendChild(undoSvgElem);
        clearButton.appendChild(clearSvgElem);

        undoButton.addEventListener("click", function () {
            sketchpad.undo();
        });

        redoButton.addEventListener("click", function () {
            sketchpad.redo();
        });

        clearButton.addEventListener("click", function () {
            sketchpad.clear();
        });

        colorPicker.addEventListener("change", function (event) {
            sketchpad.setLineColor(event.target.value);
        });


        toolsDiv.appendChild(undoButton);
        toolsDiv.appendChild(redoButton);
        toolsDiv.appendChild(clearButton);
        toolsDiv.appendChild(colorPicker);

        return toolsDiv;
    }

    /**
     * Get document annotations
     *
     * @param {function} callback
     *
     * @returns {Promise}
     */
    getAnnotations(callback) {
        let promises = [];

        this._pages.forEach((page, index) => {
            promises.push(
                page.pdfPage.getAnnotations().then((annotations) => {
                    callback(page, index, annotations);
                })
            );
        });

        return Promise.all(promises);
    }

    /**
     * Save form data
     */
    output(options = {}) {
        options.format = this._pageSizes[1] || DEFAULT_FORMAT;
        options.orientation = (this._pageSizes[1] && this._pageSizes[1][0] > this._pageSizes[1][1]) 
            ? ORIENTATION_LANDSCAPE 
            : ORIENTATION_PORTRAIT;

        return pdfFactory((pdf) => {
            let defaultFontSize = pdf.getFontSize();
            return this.getAnnotations((page, index, annotations) => {
                if (index !== 0) {
                    pdf.addPage(this._pageSizes[index] || DEFAULT_FORMAT);
                }
                
                pdf.addImage(page.canvas, 'PNG', 0, 0);
                //TODO: Needs VERY major refactoring
                annotations.forEach((annotation) => {
                    let bottom = page.pdfPage.view[3];

                    if (annotation.fieldType === 'Sig') {
                        let sketchpad = this._sketchpads.find((sketchpad) => annotation.id === sketchpad.annotation.id);
                        let img = sketchpad.sketchpad.getImage();

                        pdf.addImage(img, 'PNG', annotation.rect[0], bottom - annotation.rect[3]);
                    } else if (annotation.fieldName === 'qr_code' && this._blankDefaults.qr_code_url !== null) {
                        let canvas = document.createElement('canvas');
                        canvas.width = (annotation.rect[2] - annotation.rect[0]) * 1.333333;
                        canvas.height = (annotation.rect[3] - annotation.rect[1]) * 1.333333;

                        QRCode.toCanvas(canvas, this._blankDefaults.qr_code_url, {
                            width: canvas.width,
                            color: {
                                dark: '#005295',
                                light: '#0000'
                            }
                        }, function (error) {
                            if (error) console.error(error)

                            let img = canvas.toDataURL("image/png", 1.0);
                            pdf.addImage(img, 'JPEG', annotation.rect[0], bottom - annotation.rect[3]);
                        })
                    } else {
                        this.addAnnotation(pdf, page, annotation, defaultFontSize);
                    }

                    //Images
                    if (Array.isArray(this._images)) {
                        let image = this._images.find((image) => image.name === annotation.fieldName);

                        if (image && image.img) {
                            pdf.addImage(image.img, 'PNG', annotation.rect[0], bottom - annotation.rect[3]);
                        }
                    }
                });
            });
        }, options);
    }

    /**
     * Get form data
     *
     * @returns {object}
     */
    getFormData() {
        let data = {};

        return this.getAnnotations((page, index, annotations) => {
            annotations.forEach((annotation) => {
                let value = this.getFieldValue(page, annotation.id);
                if (value === true) {
                    data[annotation.fieldName] = true;
                } else if (value !== '' && value !== false) {
                    data[annotation.fieldName] = value;
                }
            });
        }).then(() => {
            return data;
        });
    }

    /**
     * Set form data
     *
     * @returns {object}
     */
    setFormData(data) {
        this.getAnnotations((page, index, annotations) => {
            annotations.forEach((annotation) => {
                if (annotation.fieldName in data) {
                    this.setFieldValue(page, annotation.id, data[annotation.fieldName]);
                }
            });
        })
    }


    /**
     * Print form value in resulting pdf
     *
     * @param {object} pdf
     * @param {object} page
     * @param {object} annotation
     * @param {number} defaultFontSize
     */
    addAnnotation(pdf, page, annotation, defaultFontSize) {
        let bottom = page.pdfPage.view[3];
        let value = this.getFieldValue(page, annotation.id);
        if (value === true) {
            pdf.addImage(CHECK, 'PNG', annotation.rect[0], bottom - annotation.rect[3]);
        } else if (value !== '' && value !== false && value !== undefined) {
            if (annotation.hasAppearance === true) {
                let appearance = annotation.defaultAppearance ? annotation.defaultAppearance.split(' ') : [];
                let font = appearance[1] ? Number(appearance[1]) : null;
                if (font) {
                    pdf.setFontSize(font);
                }
            } else {
                pdf.setFontSize(defaultFontSize);
            }
            pdf.text(pdf.splitTextToSize(value, annotation.rect[2] - annotation.rect[0]), annotation.rect[0], bottom - annotation.rect[3] + LINE_HEIGHT);
        }
    }

    /**
     * Get annotation field
     *
     * @param {object} page
     * @param {string} id
     *
     * @returns {object}
     */
    getField(page, id) {
        return page.annotationLayer.div.querySelector('section[data-annotation-id="' + id + '"]>*');
    }

    /**
     * Get annotation field value
     *
     * @param {object} page
     * @param {string} id
     *
     * @returns {mixed}
     */
    getFieldValue(page, id) {
        let field = this.getField(page, id);

        if (field !== null) {
            if (field.type == 'checkbox') {
                return field.checked;
            } else if (field.value !== '') {
                return field.value;
            }
        }

        return '';
    }

    /**
     * Set annotation field value
     *
     * @param {object} page
     * @param {string} id
     *
     * @param value
     * @returns {void}
     */
    setFieldValue(page, id, value) {
        let field = this.getField(page, id);

        if (field !== null) {
            if (field.type == 'checkbox') {
                field.checked = Boolean(value);
            } else {
                field.value = value;
            }
        }
    }

    /**
     * Check if the document is ready
     *
     * @returns {bool}
     */
    get ready() {
        return this._ready;
    }


    // Normalize rectangle rect=[x1, y1, x2, y2] so that (x1,y1) < (x2,y2)
    // For coordinate systems whose origin lies in the bottom-left, this
    // means normalization to (BL,TR) ordering. For systems with origin in the
    // top-left, this means (TL,BR) ordering.
    normalizeRect(rect) {
        const r = rect.slice(0); // clone rect
        if (rect[0] > rect[2]) {
            r[0] = rect[2];
            r[2] = rect[0];
        }
        if (rect[1] > rect[3]) {
            r[1] = rect[3];
            r[3] = rect[1];
        }
        return r;
    }

}

export default PdfBlank;

export {
    pdfFactory,
    pageToPdf,
    multiPagesToPdf,
};
